// Example 19_pattern_query — the fluent graph/query pattern API at scale.
//
// It builds a labelled property graph that models a software package
// dependency network, freezes it into an immutable CSR snapshot, and
// then drives a battery of MATCH-style pattern queries through the fluent
// [github.com/FlavioCFOliveira/GoGraph/graph/query] API — the same three
// capabilities the original toy demonstrated, now exercised at a scale
// where the engine's behaviour is observable:
//
//   - label predicates, intersected: (:Package) and (:Package:Deprecated);
//   - a label predicate combined with a property-equality predicate:
//     (:Package) WHERE p.ecosystem = 'go' and (:Package {license:'MIT'});
//   - a one-hop directed expansion: (:Deprecated)-->(b), the direct
//     dependencies of every deprecated package.
//
// For a handful of matched packages the example reads the matched
// properties back out (downloads, ecosystem, license) with a
// deterministic order so the read-back values are reproducible.
//
// # Model
//
//	(:Package {id, name, ecosystem, license, downloads})
//	(:Package:Deprecated {...})                          // a deterministic subset
//	(:Package)-[DEPENDS_ON]->(:Package)                  // a direct dependency
//
// id is a 16-char hex string; downloads is an int64; ecosystem and
// license are drawn from small fixed categorical sets. A package may
// additionally carry the Deprecated label. The fluent query API matches
// on node labels and node properties and expands one hop along the
// directed DEPENDS_ON edges, so the model carries exactly the typed
// fields and the directed topology those three query shapes exercise.
//
// # Topology
//
// The dependency graph is generated by Price's model — preferential
// attachment on a topological order. Nodes are created in index order;
// every edge runs from a higher index to a lower one (i -> j with j < i),
// so the graph is a DAG by construction (no dependency cycles). Each new
// package picks outDegree dependencies, choosing each target with
// probability proportional to its current in-degree plus one, which
// reproduces the heavy-tailed in-degree of a real ecosystem: a few
// foundational libraries are depended on by very many packages while most
// packages are depended on by few. Out-degree (a package's own direct
// dependency count) is a small fixed range, faithful to real ecosystems
// where the heavy tail lives on in-degree, not out-degree. The selection
// is driven entirely by a single seeded RNG, so fixing -seed fixes the
// shape exactly.
//
// # Scale
//
// Run with no flags, the example builds a small, deterministic default
// (a few thousand packages) whose fact lines a regression test pins.
// Every dimension is a flag, so the same binary scales up to a size where
// per-query latency and live-heap footprint become interesting:
//
//	go run ./examples/19_pattern_query -nodes 1000000 -seed 7
//
// The deterministic data shape and the fact lines are reproducible for a
// fixed -seed; only the telemetry (lines prefixed with "# ") varies
// between runs and machines.
//
// # Why in-memory
//
// The example targets the read-query API and its latency / live-heap
// footprint, so it builds the graph in memory through the property-graph
// API and queries it through the in-memory CSR snapshot. It does not
// exercise the WAL/recovery stack; the persistence path is demonstrated
// by examples 04, 17, 24 and 25.
package main

import (
	"context"
	"encoding/hex"
	"flag"
	"fmt"
	"io"
	"log"
	"math/rand"
	"os"
	"runtime"
	"sort"
	"time"

	"github.com/FlavioCFOliveira/GoGraph/graph/adjlist"
	"github.com/FlavioCFOliveira/GoGraph/graph/csr"
	"github.com/FlavioCFOliveira/GoGraph/graph/lpg"
	"github.com/FlavioCFOliveira/GoGraph/graph/lpg/schema"
	"github.com/FlavioCFOliveira/GoGraph/graph/query"
)

// Node labels. Centralised so the model is described in exactly one place
// and a rename surfaces as a compile error everywhere it is used.
const (
	labelPackage    = "Package"
	labelDeprecated = "Deprecated"
)

// Node property keys. Every Package carries all four.
const (
	propID        = "id"        // 16-char hex string, the unique key
	propName      = "name"      // realistic package name (may repeat)
	propEcosystem = "ecosystem" // categorical: go/npm/pypi/cargo/maven
	propLicense   = "license"   // categorical: MIT/Apache-2.0/...
	propDownloads = "downloads" // int64 popularity proxy
)

// matchEcosystem and matchLicense are the categorical values the property
// predicates select on. They are members of the fixed sets below, so the
// label+property queries always match a deterministic, non-empty subset.
const (
	matchEcosystem = "go"
	matchLicense   = "MIT"
)

// config captures every scale and shape knob. The zero value is not
// valid; build one with defaultConfig and override fields from flags (see
// main) or construct one directly (see the regression test).
type config struct {
	nodes        int   // number of :Package nodes
	outDegreeMin int   // minimum direct-dependency count per package (inclusive)
	outDegreeMax int   // maximum direct-dependency count per package (inclusive)
	deprecatedN  int   // 1-in-deprecatedN packages also carry the Deprecated label
	seed         int64 // RNG seed; fixes the deterministic data shape
}

// defaultConfig returns the small, deterministic default the regression
// test pins. It is large enough that the preferential-attachment topology
// and the label/property selectivity are exercised, yet small enough to
// build and query well under the short-layer 60 s package budget.
func defaultConfig() config {
	return config{
		nodes:        2000,
		outDegreeMin: 2,
		outDegreeMax: 6,
		deprecatedN:  8,
		seed:         1,
	}
}

// validate rejects a configuration that cannot produce the requested
// shape. It is checked once, at the boundary, before any work. An edge
// from package i may only target a lower-indexed package, so a package's
// out-degree is capped at its index; the generator clamps each draw to
// min(outDegree, i), which is why outDegreeMax need not be bounded by
// nodes here — only the basic range and positivity invariants are.
func (c config) validate() error {
	switch {
	case c.nodes <= 0:
		return fmt.Errorf("nodes must be > 0, got %d", c.nodes)
	case c.outDegreeMin < 0 || c.outDegreeMax < c.outDegreeMin:
		return fmt.Errorf("require 0 <= outDegreeMin <= outDegreeMax, got [%d,%d]", c.outDegreeMin, c.outDegreeMax)
	case c.deprecatedN <= 0:
		return fmt.Errorf("deprecatedN must be > 0, got %d", c.deprecatedN)
	}
	return nil
}

func main() {
	cfg := defaultConfig()
	flag.IntVar(&cfg.nodes, "nodes", cfg.nodes, "number of Package nodes")
	flag.IntVar(&cfg.outDegreeMin, "out-min", cfg.outDegreeMin, "minimum direct-dependency count per package")
	flag.IntVar(&cfg.outDegreeMax, "out-max", cfg.outDegreeMax, "maximum direct-dependency count per package")
	flag.IntVar(&cfg.deprecatedN, "deprecated-n", cfg.deprecatedN, "1-in-N packages are also Deprecated")
	flag.Int64Var(&cfg.seed, "seed", cfg.seed, "RNG seed (fixes the deterministic data shape)")
	flag.Parse()

	if err := run(context.Background(), os.Stdout, cfg); err != nil {
		log.Fatal(err)
	}
}

// run builds the dependency graph described by cfg, freezes it into a CSR
// snapshot, runs the fluent pattern-query battery, and writes a report to
// w. Bare lines carry deterministic facts (counts and read-back property
// values, reproducible for a fixed seed); lines prefixed with "# " carry
// volatile telemetry (durations and heap figures) that vary per run and
// per machine. All output goes to w so a test can capture and assert on
// the deterministic lines.
func run(ctx context.Context, w io.Writer, cfg config) error {
	if err := cfg.validate(); err != nil {
		return fmt.Errorf("config: %w", err)
	}

	fmt.Fprintf(w, "config.nodes=%d\n", cfg.nodes)
	fmt.Fprintf(w, "config.out_degree=[%d,%d]\n", cfg.outDegreeMin, cfg.outDegreeMax)
	fmt.Fprintf(w, "config.deprecated_n=%d\n", cfg.deprecatedN)
	fmt.Fprintf(w, "config.seed=%d\n", cfg.seed)

	base := readMem()

	g := lpg.New[string, int64](adjlist.Config{Directed: true})
	declareSchema(g)

	stats, err := build(ctx, g, cfg)
	if err != nil {
		return fmt.Errorf("build: %w", err)
	}

	// This is a build-then-query workload: the graph is fully assembled
	// above and only read from here on. Compact right-sizes the adjacency
	// backing arrays so the resident-heap figures below reflect the tight
	// arrays the query phase runs against.
	if err := ctx.Err(); err != nil {
		return err
	}
	g.AdjList().Compact(ctx)

	fmt.Fprintf(w, "nodes.packages=%d\n", stats.nodes)
	fmt.Fprintf(w, "nodes.deprecated=%d\n", stats.deprecated)
	fmt.Fprintf(w, "edges.depends_on=%d\n", stats.edges)

	built := readMem()
	fmt.Fprintf(w, "# build.elapsed=%s\n", stats.elapsed.Round(time.Millisecond))
	fmt.Fprintf(w, "# build.node_rate=%.0f nodes/s\n", rate(stats.nodes, stats.elapsed))
	fmt.Fprintf(w, "# build.edge_rate=%.0f edges/s\n", rate(stats.edges, stats.elapsed))
	fmt.Fprintf(w, "# mem.heap_alloc=%s\n", humanBytes(built.HeapAlloc))
	fmt.Fprintf(w, "# mem.heap_growth=%s\n", humanBytes(built.HeapAlloc-base.HeapAlloc))

	// Freeze the mutable builder into an immutable CSR snapshot — the
	// adjacency surface the fluent query engine traverses for one-hop
	// expansion — and report how long the freeze took.
	freezeStart := time.Now()
	c := csr.BuildFromAdjList(g.AdjList())
	freeze := time.Since(freezeStart)
	eng := query.New(g, c)
	fmt.Fprintf(w, "# csr.freeze=%s\n", freeze.Round(time.Microsecond))

	return runQueries(ctx, eng, g, w)
}

// buildStats reports the realised shape of a build (the random out-degrees
// mean the edge total is not known until the graph is materialised) plus
// the wall-clock cost.
type buildStats struct {
	nodes      int
	deprecated int
	edges      int
	elapsed    time.Duration
}

// declareSchema registers the Package/Deprecated labels and the four
// typed property keys on g. The schema is declarative documentation of
// the model's shape here (it is not installed as a write-path validator),
// matching the original example's use of the schema package.
func declareSchema(g *lpg.Graph[string, int64]) {
	s := schema.New(g.Registry(), g.PropertyKeys())
	s.RegisterLabel(labelPackage)
	s.RegisterLabel(labelDeprecated)
	// RegisterProperty only fails on a kind redeclaration, which cannot
	// happen here because each key is registered exactly once with a fixed
	// kind; the values are discarded deliberately.
	_, _ = s.RegisterProperty(propID, lpg.PropString)
	_, _ = s.RegisterProperty(propName, lpg.PropString)
	_, _ = s.RegisterProperty(propEcosystem, lpg.PropString)
	_, _ = s.RegisterProperty(propLicense, lpg.PropString)
	_, _ = s.RegisterProperty(propDownloads, lpg.PropInt64)
}

// build materialises the dependency graph described by cfg into g using
// Price's model. It first creates every package node (so DEPENDS_ON
// targets exist before edges reference them), recording each node's key,
// then adds the dependency edges from higher to lower index with
// preferential attachment by current in-degree. The build honours ctx
// cancellation on a periodic check.
func build(ctx context.Context, g *lpg.Graph[string, int64], cfg config) (buildStats, error) {
	//nolint:gosec // G404: a seeded math/rand is intentional here — the example
	// must reproduce a fixed dataset for a given -seed; crypto/rand would defeat that.
	rng := rand.New(rand.NewSource(cfg.seed))
	start := time.Now()

	keys := make([]string, cfg.nodes)
	seen := make(map[string]struct{}, cfg.nodes)

	// targets is the preferential-attachment urn: each existing node
	// appears once per incident in-edge plus once for its base weight, so
	// drawing a uniform element selects a target with probability
	// proportional to (in-degree + 1) in amortised O(1) per draw. It is
	// pre-sized to its exact final length: every node contributes one base
	// entry, and every edge contributes one in-degree entry.
	maxEdges := cfg.nodes * cfg.outDegreeMax
	targets := make([]int, 0, cfg.nodes+maxEdges)

	deprecated := 0
	edges := 0
	picked := make(map[int]struct{}, cfg.outDegreeMax)

	for i := 0; i < cfg.nodes; i++ {
		if i%checkEvery == 0 {
			if err := ctx.Err(); err != nil {
				return buildStats{}, err
			}
		}

		id := uniqueHexID(rng, seen)
		keys[i] = id
		isDeprecated := i%cfg.deprecatedN == 0
		if isDeprecated {
			deprecated++
		}
		if err := addPackage(g, id, rng, isDeprecated); err != nil {
			return buildStats{}, err
		}

		// Out-edges from i target only lower indices (keeps the graph an
		// acyclic dependency DAG), capped at the number of earlier nodes.
		degree := cfg.outDegreeMin + rng.Intn(cfg.outDegreeMax-cfg.outDegreeMin+1)
		if degree > i {
			degree = i
		}
		clear(picked)
		for len(picked) < degree {
			j := targets[rng.Intn(len(targets))]
			if _, dup := picked[j]; dup {
				continue
			}
			picked[j] = struct{}{}
			if err := g.AddEdge(id, keys[j], 1); err != nil {
				return buildStats{}, fmt.Errorf("AddEdge %s->%s: %w", id, keys[j], err)
			}
			edges++
			targets = append(targets, j) // j gained one in-edge
		}

		targets = append(targets, i) // i's base weight (in-degree + 1)
	}

	return buildStats{
		nodes:      cfg.nodes,
		deprecated: deprecated,
		edges:      edges,
		elapsed:    time.Since(start),
	}, nil
}

// checkEvery bounds how often the build polls ctx for cancellation: often
// enough that a cancelled large build stops promptly, rare enough that the
// check is free relative to the surrounding work.
const checkEvery = 4096

// addPackage adds one Package node carrying its four typed properties and,
// when deprecated, the additional Deprecated label. The property values
// are drawn from the seeded rng so the whole dataset is reproducible.
func addPackage(g *lpg.Graph[string, int64], id string, rng *rand.Rand, deprecated bool) error {
	if err := g.SetNodeLabel(id, labelPackage); err != nil {
		return fmt.Errorf("SetNodeLabel %s %s: %w", labelPackage, id, err)
	}
	if deprecated {
		if err := g.SetNodeLabel(id, labelDeprecated); err != nil {
			return fmt.Errorf("SetNodeLabel %s %s: %w", labelDeprecated, id, err)
		}
	}
	props := []struct {
		key string
		val lpg.PropertyValue
	}{
		{propID, lpg.StringValue(id)},
		{propName, lpg.StringValue(realisticName(rng))},
		{propEcosystem, lpg.StringValue(ecosystems[rng.Intn(len(ecosystems))])},
		{propLicense, lpg.StringValue(licenses[rng.Intn(len(licenses))])},
		// Downloads: a heavy-tailed popularity proxy in [0, ~10M).
		{propDownloads, lpg.Int64Value(int64(rng.Intn(10_000_000)))},
	}
	for _, p := range props {
		if err := g.SetNodeProperty(id, p.key, p.val); err != nil {
			return fmt.Errorf("SetNodeProperty %s %s: %w", p.key, id, err)
		}
	}
	return nil
}

// uniqueHexID returns a 16-character lowercase hex id (8 random bytes)
// that has not been handed out before, recording it in seen. The bytes
// come from the seeded rng (via rng.Read) so the dataset is reproducible
// and no integer-narrowing conversion is performed.
func uniqueHexID(rng *rand.Rand, seen map[string]struct{}) string {
	var b [8]byte
	for {
		_, _ = rng.Read(b[:]) // *rand.Rand.Read never returns an error
		id := hex.EncodeToString(b[:])
		if _, dup := seen[id]; dup {
			continue
		}
		seen[id] = struct{}{}
		return id
	}
}

// realisticName assembles a plausible package name of the form
// "<prefix>-<suffix>" from fixed word lists. Names are intentionally
// allowed to repeat — the unique key is the hex id, not the name.
func realisticName(rng *rand.Rand) string {
	return namePrefixes[rng.Intn(len(namePrefixes))] + "-" + nameSuffixes[rng.Intn(len(nameSuffixes))]
}

// ─────────────────────────────────────────────────────────────────────────────
// Query battery
// ─────────────────────────────────────────────────────────────────────────────

// runQueries executes the fluent pattern-query suite against eng, printing
// one deterministic count line and one volatile latency line ("# ...") per
// query, then a small set of deterministic read-back property facts.
func runQueries(ctx context.Context, eng *query.Engine[string, int64], g *lpg.Graph[string, int64], w io.Writer) error {
	// Label-only patterns: a single label scan, and two labels intersected.
	counts := []struct {
		name    string
		pattern func() *query.Pattern[string, int64]
	}{
		{"all_packages", func() *query.Pattern[string, int64] {
			return eng.Match().Vertex(query.WithLabel[string, int64](labelPackage))
		}},
		{"deprecated", func() *query.Pattern[string, int64] {
			return eng.Match().Vertex(
				query.WithLabel[string, int64](labelPackage),
				query.WithLabel[string, int64](labelDeprecated),
			)
		}},
		// Label + property-equality predicate: an ecosystem, then a license.
		{"ecosystem_go", func() *query.Pattern[string, int64] {
			return eng.Match().Vertex(
				query.WithLabel[string, int64](labelPackage),
				query.WithProperty[string, int64](propEcosystem, lpg.StringValue(matchEcosystem)),
			)
		}},
		{"license_mit", func() *query.Pattern[string, int64] {
			return eng.Match().Vertex(
				query.WithLabel[string, int64](labelPackage),
				query.WithProperty[string, int64](propLicense, lpg.StringValue(matchLicense)),
			)
		}},
	}
	for _, q := range counts {
		if err := ctx.Err(); err != nil {
			return err
		}
		start := time.Now()
		n := q.pattern().Cardinality()
		d := time.Since(start)
		fmt.Fprintf(w, "q.%s=%d\n", q.name, n)
		fmt.Fprintf(w, "# q.%s.latency=%s\n", q.name, d.Round(time.Microsecond))
	}

	// One-hop expansion: the distinct direct dependencies of every
	// deprecated package — (:Package:Deprecated)-->(b). This is the
	// capability the original toy demonstrated, now over the generated DAG.
	if err := ctx.Err(); err != nil {
		return err
	}
	start := time.Now()
	deps := eng.Match().
		Vertex(
			query.WithLabel[string, int64](labelPackage),
			query.WithLabel[string, int64](labelDeprecated),
		).
		Out().
		Cardinality()
	d := time.Since(start)
	fmt.Fprintf(w, "q.deprecated_deps=%d\n", deps)
	fmt.Fprintf(w, "# q.deprecated_deps.latency=%s\n", d.Round(time.Microsecond))

	return readBack(eng, g, w)
}

// readBack reads matched properties back out for the top packages by
// download count, demonstrating that a matched node's typed properties
// can be retrieved after a pattern query. The ordering is a total order
// (downloads DESC, id ASC) so the reported values are byte-stable for a
// fixed seed. Exactly readBackTop rows are printed.
func readBack(eng *query.Engine[string, int64], g *lpg.Graph[string, int64], w io.Writer) error {
	matched := eng.Match().Vertex(
		query.WithLabel[string, int64](labelPackage),
		query.WithProperty[string, int64](propEcosystem, lpg.StringValue(matchEcosystem)),
	).Collect()

	type row struct {
		id        string
		downloads int64
		license   string
	}
	rows := make([]row, 0, len(matched))
	for _, key := range matched {
		dl, ok := g.GetNodeProperty(key, propDownloads)
		if !ok {
			return fmt.Errorf("package %q missing property %s", key, propDownloads)
		}
		dlv, ok := dl.Int64()
		if !ok {
			return fmt.Errorf("package %q property %s is not an int64", key, propDownloads)
		}
		lic, ok := g.GetNodeProperty(key, propLicense)
		if !ok {
			return fmt.Errorf("package %q missing property %s", key, propLicense)
		}
		licv, ok := lic.String()
		if !ok {
			return fmt.Errorf("package %q property %s is not a string", key, propLicense)
		}
		rows = append(rows, row{id: key, downloads: dlv, license: licv})
	}

	// Total order: highest downloads first, id ascending as the tiebreak,
	// so the read-back is deterministic regardless of match iteration order.
	sort.Slice(rows, func(a, b int) bool {
		if rows[a].downloads != rows[b].downloads {
			return rows[a].downloads > rows[b].downloads
		}
		return rows[a].id < rows[b].id
	})

	fmt.Fprintf(w, "readback.rows=%d\n", min(readBackTop, len(rows)))
	for i := 0; i < readBackTop && i < len(rows); i++ {
		r := rows[i]
		fmt.Fprintf(w, "readback.%d=id:%s downloads:%d license:%s\n", i, r.id, r.downloads, r.license)
	}
	return nil
}

// readBackTop is how many top-by-downloads matched packages the read-back
// phase prints. Small and fixed so the deterministic fact lines stay
// compact and a regression test can pin them.
const readBackTop = 3

// ─────────────────────────────────────────────────────────────────────────────
// Telemetry helpers
// ─────────────────────────────────────────────────────────────────────────────

// readMem returns a memory snapshot after forcing a GC so HeapAlloc
// reflects live (reachable) bytes rather than floating garbage.
func readMem() runtime.MemStats {
	runtime.GC()
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	return m
}

// rate returns count/elapsed in units per second, or 0 for a zero-length
// interval.
func rate(count int, elapsed time.Duration) float64 {
	if elapsed <= 0 {
		return 0
	}
	return float64(count) / elapsed.Seconds()
}

// humanBytes formats a byte count with a binary (KiB/MiB/GiB) suffix.
func humanBytes(n uint64) string {
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := uint64(unit), 0
	for v := n / unit; v >= unit; v /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.2f %ciB", float64(n)/float64(div), "KMGTPE"[exp])
}

// ─────────────────────────────────────────────────────────────────────────────
// Realistic-data word lists and categorical sets. Fixed so the dataset is
// reproducible.
// ─────────────────────────────────────────────────────────────────────────────

// ecosystems and licenses are the small categorical sets the property
// predicates select on. matchEcosystem and matchLicense are members of
// these sets.
var ecosystems = []string{"go", "npm", "pypi", "cargo", "maven"}

var licenses = []string{"MIT", "Apache-2.0", "BSD-3-Clause", "GPL-3.0", "MPL-2.0"}

var namePrefixes = []string{
	"core", "fast", "go", "lib", "micro", "nano", "open", "pure",
	"quick", "rapid", "secure", "simple", "smart", "swift", "tiny",
	"ultra", "auto", "cloud", "data", "net", "sync", "async", "cache",
	"query", "graph", "json", "yaml", "proto", "http", "grpc",
}

var nameSuffixes = []string{
	"kit", "core", "utils", "fmt", "parse", "router", "client", "server",
	"pool", "queue", "cache", "store", "codec", "logger", "config", "auth",
	"crypto", "hash", "tree", "list", "map", "set", "stream", "buffer",
	"reader", "writer", "encoder", "decoder", "metrics", "trace",
}
