//go:build soak || nightly

// Package graph_test hosts integration tests that cannot live in
// package graph itself due to the graph → shapegen → graph import cycle.
package graph_test

import (
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/FlavioCFOliveira/GoGraph/graph"
	"github.com/FlavioCFOliveira/GoGraph/internal/shapegen"
)

// TestMapper_ShardZeroStorm verifies that 100_000 adversarial
// shard-0 preimage keys can be interned by 16 concurrent goroutines
// without deadlock and within a 60-second wall-clock deadline.
//
// The keys are generated by [shapegen.GenerateShardZeroKeys], which
// produces strings whose FNV-1a hash routes to shard 0 under the
// current [mapperShardCount] constant.  Concentrating all keys on a
// single shard maximises lock contention and exercises the
// double-checked locking in [Mapper.internSlow].
//
// After all goroutines complete, the test verifies:
//
//  1. Every key is present in the Mapper (no silent drop).
//  2. Every assigned NodeID has shard byte 0 (routing is correct).
func TestMapper_ShardZeroStorm(t *testing.T) {
	const (
		nKeys       = 100_000
		nGoroutines = 16
		deadline    = 60 * time.Second
	)

	keys := shapegen.GenerateShardZeroKeys(nKeys)
	if len(keys) < nKeys {
		t.Fatalf("GenerateShardZeroKeys returned %d keys, want %d", len(keys), nKeys)
	}

	m := graph.NewMapper[string]()

	// deadlineExceeded is set to 1 by the timer callback when the
	// wall-clock deadline fires.  Using an atomic avoids a goroutine
	// that would outlive the test and trigger goleak.
	var deadlineExceeded atomic.Int32
	timer := time.AfterFunc(deadline, func() {
		deadlineExceeded.Store(1)
	})
	defer timer.Stop()

	var wg sync.WaitGroup
	perGoroutine := nKeys / nGoroutines
	wg.Add(nGoroutines)
	for g := 0; g < nGoroutines; g++ {
		g := g
		go func() {
			defer wg.Done()
			start := g * perGoroutine
			end := start + perGoroutine
			if g == nGoroutines-1 {
				end = nKeys
			}
			for _, k := range keys[start:end] {
				if deadlineExceeded.Load() != 0 {
					t.Errorf("deadline exceeded before all keys were interned")
					return
				}
				m.Intern(k)
			}
		}()
	}
	wg.Wait()

	if deadlineExceeded.Load() != 0 {
		t.Fatalf("deadline (%v) exceeded — storm did not complete in time", deadline)
	}

	// Verify every key was interned and landed on shard 0.
	var violations int
	for _, k := range keys {
		id, ok := m.Lookup(k)
		if !ok {
			t.Errorf("key %q not found after storm", k)
			continue
		}
		if graph.MapperShardOf(id) != 0 {
			violations++
		}
	}
	if violations > 0 {
		t.Errorf("%d keys had non-zero shard byte", violations)
	}
	t.Logf("Interned %d shard-0 keys across %d goroutines successfully", nKeys, nGoroutines)
}
