// Example 08_pagerank — runs PageRank over a seeded, scale-free directed
// web and reports the most authoritative pages, most to least important.
//
// It builds a directed "web" whose in-degree distribution is heavy-tailed
// (a few authority pages everyone links to, a long tail of pages nobody
// links to), runs [centrality.PageRank] over an immutable CSR snapshot of
// it, reads the per-node ranks back through the adjacency-list [Mapper],
// and prints a deterministic top-k of pages ordered by rank. Because the
// in-degree tail is heavy, PageRank is genuinely non-uniform: a stable,
// clearly separated set of authorities emerges rather than the all-equal
// scores a symmetric cycle would give.
//
// # Model
//
//	(:page) -> (:page)   // a directed hyperlink; src endorses dst
//
// Pages are named "page%07d" in creation order. Edges point from the
// linking page to the linked page, so a page's in-degree is how many
// other pages link to it and PageRank concentrates stationary mass on
// high-in-degree pages that are themselves linked from high-mass pages.
//
// # Topology — Price's directed scale-free model
//
// The web is generated by Price's model (de Solla Price, Science 149:510,
// 1965; J. Amer. Soc. Inf. Sci. 27:292, 1976) — the canonical directed
// citation/web preferential-attachment model and the directed counterpart
// of Barabási–Albert (classic BA is undirected). Each new page emits
// links out-degree out-edges to existing pages chosen with probability
// proportional to their current in-degree plus an additive attractiveness
// constant attract, which puts the heavy tail on the IN-degree (the link
// targets) and makes even never-linked pages reachable. The resulting
// in-degree power-law exponent is gamma_in = 2 + attract/links (Newman,
// Networks 2nd ed. §14.1), so attract < links yields a tail heavier than
// BA's gamma=3 and a more concentrated PageRank top-k.
//
// Targets are sampled in O(1) amortised time per edge by the redirection
// / edge-copying technique (Newman §14.1): an append-only target list
// records every edge's destination, so a node appears in it exactly
// in-degree times and a uniform pick from the list is an in-degree-
// proportional pick — no per-node cumulative-degree scan. The whole graph
// is generated in O(V·links) = O(E) time in a single seeded math/rand
// pass, so a fixed -seed fixes the shape exactly. This design was
// confirmed with the project's graph-theory-expert sub-agent.
//
// # Scale
//
// Run with no flags the example builds a small deterministic web — 500
// pages, 4 out-links per page, attractiveness 1 (gamma_in ≈ 2.25) — that
// builds and ranks in milliseconds, well under the short-test budget. The
// earliest-created core pages accumulate the most incoming mass
// (preferential attachment rewards age), so the top-k is dominated by
// low-index pages and is stable across runs and machines for a fixed seed.
// Every dimension is a flag, so the same binary scales up to where
// PageRank's convergence cost and footprint become observable:
//
//	go run ./examples/08_pagerank -pages 1000000 -links 8 -seed 7
//
// # Output
//
// Bare lines carry deterministic facts (the top-k page ids by rank, with a
// stable tiebreak, and the count of distinct rank values), reproducible
// for a fixed -seed. Lines prefixed with "# " carry volatile telemetry —
// convergence iterations, wall-clock timing, transient allocations and
// live heap — that varies per run and per machine. A regression test pins
// the facts and ignores the telemetry.
package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"log"
	"math/rand"
	"os"
	"runtime"
	"sort"
	"time"

	"github.com/FlavioCFOliveira/GoGraph/graph"
	"github.com/FlavioCFOliveira/GoGraph/graph/adjlist"
	"github.com/FlavioCFOliveira/GoGraph/graph/csr"
	"github.com/FlavioCFOliveira/GoGraph/search/centrality"
)

// config captures every scale and shape knob of the PageRank web. The
// zero value is not valid; build one with defaultConfig and override
// fields from flags (see main) or construct one directly (see the
// regression test).
type config struct {
	pages   int   // number of pages (nodes) to generate
	links   int   // out-degree per page (out-links each new page emits)
	attract int   // Price attractiveness constant a (in-degree smoothing)
	seedNet int   // size of the seed core; the core is a directed ring
	topK    int   // how many top-ranked pages to report as facts
	seed    int64 // RNG seed; fixes the deterministic data shape
}

// defaultConfig returns the small deterministic web the regression test
// pins: 500 pages, 4 out-links each, attractiveness 1 (in-degree exponent
// gamma_in ≈ 2.25), a 5-node seed ring, reporting the top 10 pages.
func defaultConfig() config {
	return config{
		pages:   500,
		links:   4,
		attract: 1,
		seedNet: 5,
		topK:    10,
		seed:    1,
	}
}

// validate rejects a configuration that cannot produce the requested
// shape. It is checked once, at the boundary, before any work. The seed
// core must hold at least links pages so the first generated page has
// enough distinct targets to link to, and topK cannot exceed the page
// count.
func (c config) validate() error {
	switch {
	case c.pages <= 0:
		return fmt.Errorf("pages must be > 0, got %d", c.pages)
	case c.links <= 0:
		return fmt.Errorf("links must be > 0, got %d", c.links)
	case c.attract < 0:
		return fmt.Errorf("attract must be >= 0, got %d", c.attract)
	case c.seedNet < 2:
		return fmt.Errorf("seedNet must be >= 2, got %d", c.seedNet)
	case c.seedNet > c.pages:
		return fmt.Errorf("seedNet (%d) exceeds pages (%d)", c.seedNet, c.pages)
	case c.links > c.seedNet:
		return fmt.Errorf("links (%d) exceeds seedNet (%d): a new page needs that many distinct existing targets", c.links, c.seedNet)
	case c.topK <= 0:
		return fmt.Errorf("topK must be > 0, got %d", c.topK)
	case c.topK > c.pages:
		return fmt.Errorf("topK (%d) exceeds pages (%d)", c.topK, c.pages)
	}
	return nil
}

func main() {
	cfg := defaultConfig()
	flag.IntVar(&cfg.pages, "pages", cfg.pages, "number of pages (nodes) to generate")
	flag.IntVar(&cfg.links, "links", cfg.links, "out-degree per page (out-links each new page emits)")
	flag.IntVar(&cfg.attract, "attract", cfg.attract, "Price attractiveness constant a (in-degree smoothing; smaller => heavier tail)")
	flag.IntVar(&cfg.seedNet, "seed-net", cfg.seedNet, "size of the seed core (a directed ring)")
	flag.IntVar(&cfg.topK, "top-k", cfg.topK, "how many top-ranked pages to report as facts")
	flag.Int64Var(&cfg.seed, "seed", cfg.seed, "RNG seed (fixes the deterministic data shape)")
	flag.Parse()

	if err := run(context.Background(), os.Stdout, cfg); err != nil {
		log.Fatal(err)
	}
}

// run generates the scale-free web described by cfg, runs PageRank over an
// immutable CSR snapshot of it, and writes a report to w. Bare lines carry
// deterministic facts (the top-k page ids by rank and the distinct-rank
// count, reproducible for a fixed seed); lines prefixed with "# " carry
// volatile telemetry (convergence iterations, durations, allocation and
// heap figures) that varies per run and per machine. All output goes to w
// so a test can capture and assert on the deterministic lines.
func run(ctx context.Context, w io.Writer, cfg config) error {
	if err := cfg.validate(); err != nil {
		return fmt.Errorf("config: %w", err)
	}

	fmt.Fprintf(w, "config.pages=%d\n", cfg.pages)
	fmt.Fprintf(w, "config.links=%d\n", cfg.links)
	fmt.Fprintf(w, "config.attract=%d\n", cfg.attract)
	fmt.Fprintf(w, "config.seed_net=%d\n", cfg.seedNet)
	fmt.Fprintf(w, "config.top_k=%d\n", cfg.topK)
	fmt.Fprintf(w, "config.seed=%d\n", cfg.seed)

	base := readMem()

	a := adjlist.New[string, struct{}](adjlist.Config{Directed: true})
	stats, err := build(ctx, a, cfg)
	if err != nil {
		return fmt.Errorf("build: %w", err)
	}
	fmt.Fprintf(w, "nodes.pages=%d\n", stats.pages)
	fmt.Fprintf(w, "edges.links=%d\n", stats.links)

	// This is a build-then-analyse workload: the web is fully assembled
	// above and only read from here on. Compact right-sizes the adjacency
	// backing arrays before the CSR snapshot is taken so the resident-heap
	// figures reflect the tight arrays the analysis runs against.
	if err := ctx.Err(); err != nil {
		return err
	}
	a.Compact(ctx)

	c := csr.BuildFromAdjList(a)
	mapper := a.Mapper()

	start := time.Now()
	ranks, iters, err := centrality.PageRank(c, centrality.DefaultPageRankOptions())
	if err != nil {
		return fmt.Errorf("PageRank: %w", err)
	}
	prElapsed := time.Since(start)

	scored, err := rankPages(stats.pageIDs, mapper, ranks)
	if err != nil {
		return err
	}

	// Deterministic facts: the top-k page ids by rank (id tiebreak) and the
	// number of distinct rank values. PageRank scores are floats, so the
	// values themselves are volatile across machines; the ranked identity of
	// the top-k authorities is the stable, pinnable result.
	limit := cfg.topK
	if limit > len(scored) {
		limit = len(scored)
	}
	for i := 0; i < limit; i++ {
		fmt.Fprintf(w, "rank.%d=%s\n", i+1, scored[i].name)
	}
	fmt.Fprintf(w, "distinct_ranks=%d\n", distinctRanks(scored))

	// Volatile telemetry: convergence, timing, allocations, live heap.
	done := readMem()
	fmt.Fprintf(w, "# pagerank.iterations=%d\n", iters)
	fmt.Fprintf(w, "# pagerank.elapsed=%s\n", prElapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# build.elapsed=%s\n", stats.elapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# build.edge_rate=%.0f edges/s\n", rate(stats.links, stats.elapsed))
	fmt.Fprintf(w, "# mem.transient_mallocs=%d\n", done.Mallocs-base.Mallocs)
	fmt.Fprintf(w, "# mem.heap_alloc=%s\n", humanBytes(done.HeapAlloc))
	fmt.Fprintf(w, "# mem.heap_growth=%s\n", humanBytes(done.HeapAlloc-base.HeapAlloc))
	fmt.Fprintf(w, "# mem.num_gc=%d\n", done.NumGC-base.NumGC)

	// Top of the distribution as telemetry, so a reader sees the actual
	// rank values and their separation without the test pinning the floats.
	for i := 0; i < limit; i++ {
		fmt.Fprintf(w, "# rank.%d.score=%.6f\n", i+1, scored[i].rank)
	}
	return nil
}

// buildStats reports the realised shape of a build (the page and edge
// totals are deterministic for a fixed seed) plus the wall-clock cost and
// the page ids in creation order, used to resolve ranks back through the
// mapper.
type buildStats struct {
	pages   int
	links   int
	pageIDs []string // page ids in creation order; index i is page i
	elapsed time.Duration
}

// build materialises the scale-free web described by cfg into a using
// Price's directed preferential-attachment model. It first lays down a
// directed ring over the seed core (so the initial in-degrees are
// well-defined and there are no dangling pages), then adds each remaining
// page with links out-edges to existing pages drawn with probability
// proportional to (in-degree + attract). Targets are sampled by the
// redirection / edge-copying trick: targetList records every edge's
// destination, so each page appears in it exactly in-degree times and a
// uniform pick from it is an in-degree-proportional pick — giving O(1)
// amortised sampling per edge and an overall O(V·links) single seeded
// pass. The build honours ctx cancellation on a periodic check.
func build(ctx context.Context, a *adjlist.AdjList[string, struct{}], cfg config) (buildStats, error) {
	//nolint:gosec // G404: a seeded math/rand is intentional here — the example
	// must reproduce a fixed web for a given -seed; crypto/rand would defeat that.
	rng := rand.New(rand.NewSource(cfg.seed))
	start := time.Now()

	pageIDs := make([]string, cfg.pages)
	for i := range pageIDs {
		pageIDs[i] = pageID(i)
	}

	// targetList is the append-only edge-destination log that powers
	// in-degree-proportional sampling (the redirection trick). It is pre-
	// sized to the exact final edge count: seedNet ring edges plus links per
	// generated page.
	edges := cfg.seedNet + (cfg.pages-cfg.seedNet)*cfg.links
	targetList := make([]int, 0, edges)
	linkCount := 0

	// Seed core: a directed ring 0->1->...->(seedNet-1)->0. Every core page
	// gets exactly one in-edge, so the early preferential picks are well
	// defined and no core page is left dangling.
	for i := 0; i < cfg.seedNet; i++ {
		dst := (i + 1) % cfg.seedNet
		if err := a.AddEdge(pageIDs[i], pageIDs[dst], struct{}{}); err != nil {
			return buildStats{}, fmt.Errorf("AddEdge ring %s->%s: %w", pageIDs[i], pageIDs[dst], err)
		}
		targetList = append(targetList, dst)
		linkCount++
	}

	// Grown pages: each picks links distinct existing targets ∝ (in-degree +
	// attract) via the redirection mixture, then commits its out-edges.
	// chosenSet rejects self-links and duplicate targets within one page;
	// chosenList preserves a deterministic insertion order. Committing edges
	// from the slice (never by ranging the map) keeps the adjacency, and
	// hence PageRank's float summation order over the resulting CSR,
	// reproducible for a fixed seed — Go map iteration order is randomised
	// and would otherwise make the ranks vary run to run.
	chosenSet := make(map[int]struct{}, cfg.links)
	chosenList := make([]int, 0, cfg.links)
	for i := cfg.seedNet; i < cfg.pages; i++ {
		if i%checkEvery == 0 {
			if err := ctx.Err(); err != nil {
				return buildStats{}, err
			}
		}
		clear(chosenSet)
		chosenList = chosenList[:0]
		for len(chosenList) < cfg.links {
			t := pickTarget(rng, targetList, i, cfg.attract)
			if _, dup := chosenSet[t]; dup {
				continue
			}
			chosenSet[t] = struct{}{}
			chosenList = append(chosenList, t)
		}
		for _, t := range chosenList {
			if err := a.AddEdge(pageIDs[i], pageIDs[t], struct{}{}); err != nil {
				return buildStats{}, fmt.Errorf("AddEdge %s->%s: %w", pageIDs[i], pageIDs[t], err)
			}
			targetList = append(targetList, t)
			linkCount++
		}
	}

	return buildStats{
		pages:   cfg.pages,
		links:   linkCount,
		pageIDs: pageIDs,
		elapsed: time.Since(start),
	}, nil
}

// pickTarget returns one existing page index (in [0, n)) drawn with
// probability proportional to (in-degree + attract), excluding the new
// page n itself (which has no in-edges yet so the targetList branch never
// yields it; the uniform branch is rejected by the caller's set when it
// does). It implements the Price redirection mixture: with probability
// attract*n/(attract*n + len(targetList)) it draws a node uniformly (the
// "+attract" smoothing that keeps zero-in-degree pages reachable),
// otherwise it copies a uniform element of targetList (an in-degree-
// proportional pick). The caller rejects self-links and duplicates by
// inserting into a set, so a redrawn collision is cheap and rare for
// links ≪ n.
func pickTarget(rng *rand.Rand, targetList []int, n, attract int) int {
	smoothing := attract * n
	if rng.Intn(smoothing+len(targetList)) < smoothing {
		return rng.Intn(n) // uniform "+attract" branch
	}
	return targetList[rng.Intn(len(targetList))] // in-degree-proportional copy
}

// checkEvery bounds how often the build polls ctx for cancellation: often
// enough that a cancelled large build stops promptly, rare enough that the
// check is free relative to the surrounding work.
const checkEvery = 4096

// pageID formats a page's creation-order index as a fixed-width,
// lexicographically sortable id ("page0000042"). Fixed width keeps the
// id-tiebreak order (used when two pages tie on rank) identical to the
// numeric order, so the deterministic top-k facts are stable.
func pageID(i int) string {
	return fmt.Sprintf("page%07d", i)
}

// scored pairs a page id with its PageRank value for ranking.
type scored struct {
	name string
	rank float64
}

// rankPages resolves each page's rank out of the by-NodeID rank slice
// through the mapper and returns them sorted descending by rank, breaking
// ties by ascending page id. The rank slice is indexed by NodeID and
// rounds up to MaxNodeID across the sharded Mapper space, so it contains
// ghost slots for NodeIDs no page occupies; resolving the live pages
// through the mapper reads only their ranks.
func rankPages(pageIDs []string, mapper *graph.Mapper[string], ranks []float64) ([]scored, error) {
	scores := make([]scored, 0, len(pageIDs))
	for _, name := range pageIDs {
		id, ok := mapper.Lookup(name)
		if !ok {
			return nil, fmt.Errorf("page %q not found in graph", name)
		}
		scores = append(scores, scored{name: name, rank: ranks[id]})
	}
	sort.Slice(scores, func(i, j int) bool {
		if scores[i].rank != scores[j].rank {
			return scores[i].rank > scores[j].rank
		}
		return scores[i].name < scores[j].name
	})
	return scores, nil
}

// distinctRanks counts the number of distinct PageRank values across
// scored. A scale-free web produces many distinct authority ranks at the
// head and a large block of pages tied at the teleport floor in the tail,
// so this is a stable, deterministic summary of how non-uniform the
// distribution is. scored is assumed sorted by rank (rankPages guarantees
// it), so equal values are adjacent.
func distinctRanks(scores []scored) int {
	if len(scores) == 0 {
		return 0
	}
	count := 1
	for i := 1; i < len(scores); i++ {
		if scores[i].rank != scores[i-1].rank {
			count++
		}
	}
	return count
}

// ─────────────────────────────────────────────────────────────────────────────
// Telemetry helpers
// ─────────────────────────────────────────────────────────────────────────────

// readMem returns a memory snapshot after forcing a GC so HeapAlloc
// reflects live (reachable) bytes rather than floating garbage.
func readMem() runtime.MemStats {
	runtime.GC()
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	return m
}

// rate returns count/elapsed in units per second, or 0 for a zero-length
// interval.
func rate(count int, elapsed time.Duration) float64 {
	if elapsed <= 0 {
		return 0
	}
	return float64(count) / elapsed.Seconds()
}

// humanBytes formats a byte count with a binary (KiB/MiB/GiB) suffix.
func humanBytes(n uint64) string {
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := uint64(unit), 0
	for v := n / unit; v >= unit; v /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.2f %ciB", float64(n)/float64(div), "KMGTPE"[exp])
}
