"""SuiteSparse:GraphBLAS baseline for the comparison benchmark suite (task #180).

Builds the same deterministic random graph used by the NetworkX baseline
(``bench/comparison/networkx_baseline.py``) and times BFS, single-source
shortest paths (Bellman-Ford with non-negative weights — semantically
equivalent to Dijkstra for this input) and PageRank using the SuiteSparse:
GraphBLAS C library exposed through ``python-graphblas`` /
``graphblas-algorithms``. Output is plain text; the comparison table in
``docs/benchmarks/comparison.md`` is regenerated by hand from the printed
numbers.

The graph topology must remain in lock-step with NetworkX (same RNG and
seed) so that the two baselines benchmark structurally identical work.
The Go side uses a different PRNG (math/rand/v2 with PCG(31, 1)); we
compare statistical equivalents (same node count, edge count and degree
distribution), not bit-identical graphs.
"""

from __future__ import annotations

import random
import time

import graphblas_algorithms as ga
import networkx as nx
import suitesparse_graphblas as ssgb


N = 1 << 14  # 16k nodes — matches the Go and NetworkX baselines.
E = 4 * N    # 64k edges.
SEED = 31


def build_graph() -> ga.DiGraph:
    rng = random.Random(SEED)
    g = nx.DiGraph()
    g.add_nodes_from(range(N))
    for _ in range(E):
        u = rng.randrange(N)
        v = rng.randrange(N)
        w = rng.randrange(100) + 1
        g.add_edge(u, v, weight=w)
    return ga.DiGraph.from_networkx(g, weight="weight")


def time_call(label: str, build, run, repeats: int = 3) -> float:
    """Time `run(build())` `repeats` times; report the best.

    The graph is rebuilt between iterations to prevent
    graphblas-algorithms from reusing warmed property caches across
    measurements, which would inflate later runs and break apples-to-
    apples comparison against the NetworkX baseline (which also pays
    its own per-call setup).
    """
    best = float("inf")
    for _ in range(repeats):
        G = build()
        t0 = time.perf_counter()
        run(G)
        dt = time.perf_counter() - t0
        if dt < best:
            best = dt
    print(f"{label:<32s} best of {repeats}: {best*1000:.3f} ms")
    return best


def main() -> None:
    sample = build_graph()
    print(f"SuiteSparse:GraphBLAS {ssgb.__version__} | "
          f"python-graphblas {ga.__version__} | "
          f"n={sample._A.nrows} m={sample._A.nvals}")
    del sample

    src = 0
    # BFS: full reachable enumeration from src (layer set covering every
    # vertex reachable from src). The Go side measures the equivalent
    # full BFS via search.BFS.
    time_call(
        "BFS                            ",
        build_graph,
        lambda G: list(ga.bfs_layers(G, [src])),
    )
    # Single-source shortest path length from src. Weights are positive
    # in this graph, so Bellman-Ford and Dijkstra return the same map.
    # graphblas-algorithms ships SSSP under the Bellman-Ford name.
    time_call(
        "Dijkstra single-source         ",
        build_graph,
        lambda G: ga.single_source_bellman_ford_path_length(G, src),
    )
    # PageRank: damping 0.85, max_iter 30, tol 1e-6 — identical to the
    # NetworkX and Go invocations.
    time_call(
        "PageRank                       ",
        build_graph,
        lambda G: ga.pagerank(G, alpha=0.85, max_iter=30, tol=1e-6),
    )


if __name__ == "__main__":
    main()
