"""NetworkX baseline for the comparison benchmark suite (task #159).

Builds the same deterministic random graph used by the Go side
(`bench/comparison/gograph_baseline.go`) and times BFS, SSSP
(Dijkstra) and PageRank on it. Output is plain text; the comparison
table in docs/benchmarks/comparison.md is regenerated by hand from
the printed numbers.
"""

from __future__ import annotations

import random
import time

import networkx as nx


N = 1 << 14  # 16k nodes
E = 4 * N    # 64k edges
SEED = 31


def build_graph() -> nx.DiGraph:
    rng = random.Random(SEED)
    g = nx.DiGraph()
    g.add_nodes_from(range(N))
    for _ in range(E):
        u = rng.randrange(N)
        v = rng.randrange(N)
        w = rng.randrange(100) + 1
        g.add_edge(u, v, weight=w)
    return g


def time_call(label: str, fn, repeats: int = 3) -> float:
    best = float("inf")
    for _ in range(repeats):
        t0 = time.perf_counter()
        fn()
        dt = time.perf_counter() - t0
        if dt < best:
            best = dt
    print(f"{label:<32s} best of {repeats}: {best*1000:.2f} ms")
    return best


def main() -> None:
    g = build_graph()
    print(f"NetworkX {nx.__version__} | n={g.number_of_nodes()} m={g.number_of_edges()}")

    src = 0
    time_call("BFS                            ", lambda: list(nx.bfs_edges(g, src)))
    time_call("Dijkstra single-source         ",
              lambda: nx.single_source_dijkstra_path_length(g, src))
    time_call("PageRank                       ",
              lambda: nx.pagerank(g, alpha=0.85, max_iter=30, tol=1e-6))


if __name__ == "__main__":
    main()
