// Example 18_oocore_pipeline — the full out-of-core (Tier 2) pipeline:
// generate a directed web-link graph as a CSV edge list, ingest it through
// the CSV reader, freeze it into a CSR snapshot, persist that snapshot as an
// on-disk csrfile, re-open the file by mmap, and run semi-external BFS plus
// PageRank directly over the mapped region.
//
// # What it demonstrates
//
// This is the complete five-stage out-of-core flow, end to end:
//
//	CSV bytes -> adjacency list -> CSR snapshot -> csrfile (disk) -> mmap -> {BFS, PageRank}
//
// Example 05 builds the adjacency directly in memory; this example extends it
// by routing the same scale-free graph through the CSV interchange stage
// first, so the whole ingest path is exercised. The CSV reader interns each
// page name to a compact NodeID and returns an in-memory adjacency list;
// [csr.BuildFromAdjList] freezes it into an immutable Tier 1 CSR snapshot;
// [csrfile.WriteToFile] persists that snapshot to disk in the Tier 2 binary
// format; and [csrfile.Open] re-attaches it by mmap. From that point the graph
// is queried straight out of the mapped pages: the semi-external
// [extern.BFSCtx] and [extern.PageRankCtx] keep only vertex-sized auxiliary
// state (a visited bitset, the rank vector) in RAM while streaming the
// adjacency from the mapped file. That is the headline out-of-core advantage
// this example measures: the on-disk adjacency dwarfs the resident heap.
//
// The csrfile preserves NodeIDs across the mmap boundary but drops the
// page-name -> NodeID mapping, so the BFS needs a known numeric seed. The
// example therefore captures the seed page's NodeID from the CSV reader's
// mapper before the adjacency (and its mapper) is discarded — exactly the
// pattern a real out-of-core consumer must follow.
//
// # Model
//
// The dataset is a directed, scale-free hyperlink graph generated by Price's
// model (de Solla Price, 1965/1976) — the directed preferential-attachment
// process that is the canonical domain for PageRank. Pages arrive in id order
// 0..N-1; each arriving page emits m citation out-links to distinct earlier
// pages, choosing each target with probability proportional to its current
// in-degree plus a small attractiveness constant a (in-degree exponent
// gamma_in = 2 + a/m). This produces a heavy-tailed in-degree distribution: a
// few early-arriving pages accrue most inbound links and become high-PageRank
// authorities, while the bulk hold near-uniform low rank. Because the
// authorities separate from the bulk by a wide margin, the top-k
// highest-PageRank node ids (tie-broken by ascending id) are a stable,
// meaningful fact.
//
// Pure citation edges always point from a newer page to an older one, which
// makes the graph a shallow DAG: forward BFS from an old page reaches almost
// nothing. To give the semi-external BFS a meaningful, stable reachable count,
// each arriving page also receives, with probability navFrac, one extra
// "navigation" link from a uniformly random earlier page (older -> newer).
// These forward links build long forward paths without disturbing the
// in-degree authority tail. The BFS is seeded from a fixed mid-graph "portal"
// page (id N/4, never the oldest page, which is a pure sink), from which a
// large but bounded fraction of the graph is reachable.
//
// Determinism. The whole graph is drawn from a single math/rand source seeded
// from cfg.seed, the build is single-threaded, edges are emitted in draw
// order, and the CSV is written in that same order — so the realised shape,
// the BFS reachable count, and the PageRank top-k are byte-identical across
// machines for a fixed -seed. Only the telemetry (lines prefixed "# ") varies
// between runs and machines.
//
// # Scale
//
// Run with no flags, the example builds a small deterministic default (4000
// pages, ~16k citation edges plus ~2k navigation edges) that completes in
// milliseconds — the size the regression test pins. The same binary scales up
// to where the out-of-core footprint advantage is observable:
//
//	go run ./examples/18_oocore_pipeline -nodes 2000000 -out-degree 8
//
// At two million pages and eight out-links each the on-disk csrfile is on the
// order of ~270 MiB while the resident rank vector is only ~16 MiB — a
// disk-over-heap advantage of roughly 17x that widens as the graph grows. The
// adjacency lives on disk, not in RAM.
package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"io"
	"log"
	"math/rand"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"time"

	"github.com/FlavioCFOliveira/GoGraph/graph"
	"github.com/FlavioCFOliveira/GoGraph/graph/csr"
	"github.com/FlavioCFOliveira/GoGraph/graph/io/csv"
	"github.com/FlavioCFOliveira/GoGraph/search/extern"
	"github.com/FlavioCFOliveira/GoGraph/store/csrfile"
)

// config captures every scale and shape knob of the pipeline. The zero value
// is not valid; build one with defaultConfig and override fields from flags
// (see main) or construct one directly (see the regression test).
type config struct {
	nodes      int     // number of pages in the generated web graph
	outDegree  int     // citation out-links emitted per arriving page (Price's m)
	attractive int64   // additive attractiveness constant (Price's a; >= 0)
	navFrac    float64 // probability an arriving page also gets one forward "navigation" link
	topK       int     // number of highest-PageRank nodes to report as facts
	seed       int64   // RNG seed; fixes the deterministic data shape
}

// defaultConfig returns the small, deterministic default the regression test
// pins: a 4000-page scale-free web graph with four citation out-links per page
// and a navigation link on half the pages, which builds, persists, mmaps, and
// queries in milliseconds yet still separates a clear top-k of authorities
// from the bulk and yields a stable, non-trivial BFS reachable count.
func defaultConfig() config {
	return config{
		nodes:      4000,
		outDegree:  4,
		attractive: 1,
		navFrac:    0.5,
		topK:       10,
		seed:       7,
	}
}

// validate rejects a configuration that cannot produce the requested shape. It
// is checked once, at the boundary, before any work. Price's model needs at
// least outDegree existing pages for the first arriving page to find distinct
// targets, so nodes must exceed outDegree; the attractiveness constant must be
// positive for the integer mixture draw to be well-defined; navFrac is a
// probability in [0,1]; and topK cannot exceed the node count.
func (c config) validate() error {
	switch {
	case c.nodes <= 0:
		return fmt.Errorf("nodes must be > 0, got %d", c.nodes)
	case c.outDegree <= 0:
		return fmt.Errorf("out-degree must be > 0, got %d", c.outDegree)
	case c.nodes <= c.outDegree:
		return fmt.Errorf("nodes (%d) must exceed out-degree (%d): not enough targets", c.nodes, c.outDegree)
	case c.attractive <= 0:
		return fmt.Errorf("attractiveness must be > 0, got %d", c.attractive)
	case c.navFrac < 0 || c.navFrac > 1:
		return fmt.Errorf("nav-frac must be within [0,1], got %g", c.navFrac)
	case c.topK <= 0:
		return fmt.Errorf("top-k must be > 0, got %d", c.topK)
	case c.topK > c.nodes:
		return fmt.Errorf("top-k (%d) exceeds nodes (%d)", c.topK, c.nodes)
	}
	return nil
}

func main() {
	cfg := defaultConfig()
	flag.IntVar(&cfg.nodes, "nodes", cfg.nodes, "number of pages in the web graph")
	flag.IntVar(&cfg.outDegree, "out-degree", cfg.outDegree, "citation out-links per arriving page (Price's m)")
	flag.Int64Var(&cfg.attractive, "attractiveness", cfg.attractive, "additive attractiveness constant (Price's a; > 0)")
	flag.Float64Var(&cfg.navFrac, "nav-frac", cfg.navFrac, "probability an arriving page also gets a forward navigation link")
	flag.IntVar(&cfg.topK, "top-k", cfg.topK, "number of highest-PageRank node ids to report")
	flag.Int64Var(&cfg.seed, "seed", cfg.seed, "RNG seed (fixes the deterministic data shape)")
	flag.Parse()

	if err := run(context.Background(), os.Stdout, cfg); err != nil {
		log.Fatal(err)
	}
}

// run drives the full out-of-core pipeline described by cfg and writes a
// report to w. It generates the scale-free web graph as a CSV edge list,
// ingests it through the CSV reader, freezes the adjacency into a CSR
// snapshot, persists that snapshot as a Tier 2 csrfile, re-opens the file via
// mmap, and runs semi-external BFS plus PageRank over the mapped region.
//
// Bare lines carry deterministic facts (counts, the BFS reachable count, and
// the PageRank top-k node ids — all reproducible for a fixed seed); lines
// prefixed with "# " carry volatile telemetry (per-stage wall-clock and the
// disk-vs-heap footprint) that varies per run and per machine. All output goes
// to w so a test can capture and assert on the deterministic lines. run
// returns wrapped errors rather than terminating the process and honours ctx
// cancellation.
//
// The csrfile is written under an os.MkdirTemp directory whose absolute path
// differs on every run, so run never prints that path; every fact line it
// emits is byte-stable.
func run(ctx context.Context, w io.Writer, cfg config) error {
	if err := cfg.validate(); err != nil {
		return fmt.Errorf("config: %w", err)
	}

	fmt.Fprintf(w, "config.nodes=%d\n", cfg.nodes)
	fmt.Fprintf(w, "config.out_degree=%d\n", cfg.outDegree)
	fmt.Fprintf(w, "config.attractiveness=%d\n", cfg.attractive)
	fmt.Fprintf(w, "config.nav_frac=%g\n", cfg.navFrac)
	fmt.Fprintf(w, "config.top_k=%d\n", cfg.topK)
	fmt.Fprintf(w, "config.seed=%d\n", cfg.seed)

	dir, err := os.MkdirTemp("", "gograph-ex18-")
	if err != nil {
		return fmt.Errorf("MkdirTemp: %w", err)
	}
	defer func() { _ = os.RemoveAll(dir) }()
	path := filepath.Join(dir, "graph.csr")

	// Stage 1 — generate the directed scale-free web graph and serialise it
	// to an in-memory CSV edge list. seedPage is the page name the BFS is
	// later seeded from; csvBytes is the size of the serialised CSV input.
	csvStart := time.Now()
	csvBuf, seedPage, genEdges := generateCSV(ctx, cfg)
	if err := ctx.Err(); err != nil {
		return err
	}
	csvBytes := uint64(csvBuf.Len()) //nolint:gosec // G115: a buffer length is non-negative

	// Stage 1 (cont.) — ingest the CSV through the edge-list reader, which
	// interns each page name to a compact NodeID and returns an in-memory
	// adjacency list.
	adj, nEdges, err := csv.ReadIntoCtx(ctx, csvBuf, csv.DefaultOptions())
	if err != nil {
		return fmt.Errorf("csv.ReadIntoCtx: %w", err)
	}
	csvElapsed := time.Since(csvStart)

	// Capture the seed page's NodeID before the adjacency (and its mapper) is
	// discarded: the csrfile preserves NodeIDs across the mmap boundary but
	// drops the name -> NodeID mapping, so the BFS below needs this numeric
	// seed.
	seedID, ok := adj.Mapper().Lookup(seedPage)
	if !ok {
		return fmt.Errorf("seed page %q not interned", seedPage)
	}

	// Stage 2 — freeze the adjacency into an immutable Tier 1 CSR snapshot.
	csrStart := time.Now()
	c := csr.BuildFromAdjList(adj)
	csrElapsed := time.Since(csrStart)

	fmt.Fprintf(w, "csv.edges=%d\n", nEdges)
	fmt.Fprintf(w, "csr.order=%d\n", c.Order())
	fmt.Fprintf(w, "csr.size=%d\n", c.Size())

	// Stage 3 — write the CSR to disk in the csrfile binary format. The write
	// is atomic (write .tmp, fsync, rename). Measure the resulting on-disk
	// size: this is the adjacency footprint that, at scale, dwarfs the
	// resident auxiliary state.
	if err := ctx.Err(); err != nil {
		return err
	}
	writeStart := time.Now()
	if _, err := csrfile.WriteToFile(path, c); err != nil {
		return fmt.Errorf("csrfile.WriteToFile: %w", err)
	}
	writeElapsed := time.Since(writeStart)
	diskBytes, err := fileSize(path)
	if err != nil {
		return err
	}

	// Stage 4 — re-open the file via mmap and hint SEQUENTIAL access so the OS
	// reads ahead while the queries stream the adjacency. The mmap call maps
	// the whole file into the address space without reading it into the heap;
	// time it to show that re-attaching an on-disk graph is near-instant.
	mmapStart := time.Now()
	r, err := csrfile.Open(path)
	if err != nil {
		return fmt.Errorf("csrfile.Open: %w", err)
	}
	defer func() { _ = r.Close() }()
	if err := r.SetHint(csrfile.AccessSequential); err != nil {
		return fmt.Errorf("SetHint: %w", err)
	}
	mmapElapsed := time.Since(mmapStart)

	// Stage 5a — semi-external BFS from the portal page. Only the visited
	// bitset and frontier live in RAM; the adjacency streams from the mapped
	// file. BFSCtx honours ctx cancellation once per BFS level.
	bfsStart := time.Now()
	reached := 0
	if err := extern.BFSCtx(ctx, r, seedID, func(_ graph.NodeID, _ int) bool {
		reached++
		return true
	}); err != nil {
		return fmt.Errorf("extern.BFSCtx: %w", err)
	}
	bfsElapsed := time.Since(bfsStart)

	// Stage 5b — semi-external PageRank over the same mapped region. Only the
	// rank vector lives in RAM; the adjacency streams from the file each
	// iteration. PageRankCtx honours ctx cancellation at every iteration.
	prStart := time.Now()
	ranks, iters, err := extern.PageRankCtx(ctx, r, extern.DefaultPageRankOptions())
	if err != nil {
		return fmt.Errorf("extern.PageRankCtx: %w", err)
	}
	prElapsed := time.Since(prStart)

	// Resident heap after the computation, forcing a GC first so HeapAlloc
	// reflects live bytes. The rank vector is the dominant query-time
	// allocation, so its size is the in-RAM working set we contrast with the
	// on-disk adjacency.
	mem := readMem()
	rankVecBytes := uint64(len(ranks)) * 8 //nolint:gosec // G115: len is non-negative

	// Deterministic results. The BFS reachable count and the PageRank top-k
	// node ids are stable for a fixed seed; the top-k ids separate the
	// authorities from the bulk by a wide margin and ties are broken by
	// ascending id (see topPageRank).
	fmt.Fprintf(w, "bfs.seed_node=%d\n", seedID)
	fmt.Fprintf(w, "bfs.reachable=%d\n", reached)

	top := topPageRank(ranks, cfg.topK)
	if len(top) == 0 {
		return fmt.Errorf("PageRank produced no live ranks")
	}
	for i, id := range top {
		fmt.Fprintf(w, "pagerank.top%d=%d\n", i, id)
	}

	fmt.Fprintf(w, "# gen.edges=%d\n", genEdges)
	fmt.Fprintf(w, "# stage.csv_ingest=%s\n", csvElapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# stage.csr_build=%s\n", csrElapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# stage.csrfile_write=%s\n", writeElapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# stage.mmap_open=%s\n", mmapElapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# stage.bfs=%s\n", bfsElapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# stage.pagerank=%s\n", prElapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# disk.csv_input=%s\n", humanBytes(csvBytes))
	fmt.Fprintf(w, "# disk.csrfile=%s\n", humanBytes(diskBytes))
	fmt.Fprintf(w, "# mem.rank_vector=%s\n", humanBytes(rankVecBytes))
	fmt.Fprintf(w, "# mem.heap_alloc=%s\n", humanBytes(mem.HeapAlloc))
	fmt.Fprintf(w, "# ooc.disk_over_rank_vector=%.1fx\n", safeDiv(float64(diskBytes), float64(rankVecBytes)))
	fmt.Fprintf(w, "# pagerank.iterations=%d\n", iters)
	return nil
}

// generateCSV builds the directed scale-free web graph described by cfg using
// Price's model (directed preferential attachment) augmented with forward
// navigation links, and serialises it to an in-memory CSV edge list
// ("src,dst,1" per line). It returns the CSV buffer, the page name the BFS
// should be seeded from (id N/4, the mid-graph "portal"), and the number of
// edges written.
//
// Pages arrive in id order. A fully-wired seed core of outDegree pages is laid
// down first so the early target draws are well-defined; then each subsequent
// page v emits outDegree citation out-links to distinct earlier pages, each
// target chosen with probability proportional to its current in-degree plus
// the attractiveness constant. With probability navFrac, page v additionally
// receives one navigation in-link from a uniformly random earlier page, giving
// the forward reachability the BFS measures.
//
// Determinism. The whole graph is drawn from a single math/rand source seeded
// from cfg.seed, the build is single-threaded, and every edge is written to
// the CSV in the order it was drawn (never iterated from a map, whose order is
// randomised in Go) — so the serialised CSV, and hence every fact the pipeline
// reports, is byte-identical across machines for a fixed seed.
//
// Complexity is O(nodes * outDegree) = O(edges). The edge-copying target list
// copyTargets makes in-degree-proportional selection O(1) per pick: each
// citation edge's destination appears in it once, so a uniform draw from it is
// automatically proportional to in-degree.
func generateCSV(ctx context.Context, cfg config) (*bytes.Buffer, string, int) {
	//nolint:gosec // G404: a seeded math/rand is intentional here — the example
	// must reproduce a fixed dataset for a given -seed; crypto/rand would defeat that.
	rng := rand.New(rand.NewSource(cfg.seed))

	var buf bytes.Buffer
	edges := 0
	emit := func(src, dst int) {
		buf.WriteString(pageName(src))
		buf.WriteByte(',')
		buf.WriteString(pageName(dst))
		buf.WriteString(",1\n")
		edges++
	}

	m := cfg.outDegree
	// copyTargets holds one entry per existing citation edge: the edge's
	// destination. A page therefore appears in it exactly citation-in-degree
	// times, so a uniform draw is in-degree-proportional.
	copyTargets := make([]int, 0, cfg.nodes*m)

	// Seed core: the first m pages, wired so that page v links to every
	// earlier page u < v. This bootstraps copyTargets so the preferential
	// draws below always have a non-empty in-degree pool to sample.
	for v := 1; v < m; v++ {
		for u := 0; u < v; u++ {
			emit(v, u)
			copyTargets = append(copyTargets, u)
		}
	}

	targets := make([]int, 0, m)
	seen := make(map[int]struct{}, m)
	for v := m; v < cfg.nodes; v++ {
		if v%checkEvery == 0 {
			if err := ctx.Err(); err != nil {
				return &buf, pageName(cfg.nodes / 4), edges
			}
		}
		targets = targets[:0]
		clear(seen)
		// Draw m distinct citation targets. The mixture weight at v's arrival
		// is attractive*v (one unit of attractiveness per existing page 0..v-1)
		// plus len(copyTargets) (one per existing citation edge). A single
		// integer draw over that total picks either the uniform-page branch or
		// the in-degree-proportional copy branch, with no floating-point bias.
		for len(targets) < m {
			total := cfg.attractive*int64(v) + int64(len(copyTargets))
			r := rng.Int63n(total)
			var t int
			if r < cfg.attractive*int64(v) {
				t = int(r / cfg.attractive)
			} else {
				t = copyTargets[r-cfg.attractive*int64(v)]
			}
			if t == v {
				continue // belt-and-braces: t < v always holds here
			}
			if _, dup := seen[t]; dup {
				continue // distinct citation targets per arriving page
			}
			seen[t] = struct{}{}
			targets = append(targets, t)
		}
		// Emit citations in draw order (fixed), updating copyTargets so later
		// pages see the new in-edges.
		for _, t := range targets {
			emit(v, t)
			copyTargets = append(copyTargets, t)
		}
		// Navigation link: with probability navFrac, a uniformly random earlier
		// page links forward to v. This injects forward paths (older -> newer)
		// so the BFS reaches a large but bounded fraction of the graph. The
		// draw is taken unconditionally (even when it will not be used) so that
		// adding or removing navigation never shifts the citation RNG stream.
		s := rng.Intn(v)
		if rng.Float64() < cfg.navFrac {
			emit(s, v)
		}
	}
	return &buf, pageName(cfg.nodes / 4), edges
}

// checkEvery bounds how often generateCSV polls ctx for cancellation: often
// enough that a cancelled multi-million-page build stops promptly, rare enough
// that the check is free relative to the surrounding work.
const checkEvery = 4096

// pageName formats a page id as a stable, zero-padded "page-NNNNNN" name. The
// fixed width keeps the CSV columns aligned and the names sortable, and the
// formatting is pure (no RNG), so it never disturbs the deterministic shape.
func pageName(id int) string {
	return "page-" + strconv.Itoa(id)
}

// topPageRank returns the ids of the k highest-PageRank live nodes, in
// descending rank order, ties broken by ascending node id. The rank slice is
// indexed by NodeID and its length is the sharded, MaxNodeID-rounded vertex
// count, so it carries ghost slots (zero rank) beyond the live nodes; those
// are skipped. The ascending-id tie-break is total and machine-independent, so
// the result is stable for a fixed seed.
func topPageRank(ranks []float64, k int) []graph.NodeID {
	type nodeRank struct {
		id   graph.NodeID
		rank float64
	}
	live := make([]nodeRank, 0, len(ranks))
	for i, x := range ranks {
		if x == 0 {
			continue
		}
		live = append(live, nodeRank{id: graph.NodeID(i), rank: x}) //nolint:gosec // G115: index is non-negative
	}
	sort.Slice(live, func(i, j int) bool {
		if live[i].rank != live[j].rank {
			return live[i].rank > live[j].rank
		}
		return live[i].id < live[j].id
	})
	if k > len(live) {
		k = len(live)
	}
	out := make([]graph.NodeID, k)
	for i := 0; i < k; i++ {
		out[i] = live[i].id
	}
	return out
}

// ─────────────────────────────────────────────────────────────────────────────
// Telemetry helpers
// ─────────────────────────────────────────────────────────────────────────────

// readMem returns a memory snapshot after forcing a GC so HeapAlloc reflects
// live (reachable) bytes rather than floating garbage.
func readMem() runtime.MemStats {
	runtime.GC()
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	return m
}

// fileSize returns the size of the file at path in bytes.
func fileSize(path string) (uint64, error) {
	fi, err := os.Stat(path)
	if err != nil {
		return 0, fmt.Errorf("stat %s: %w", filepath.Base(path), err)
	}
	return uint64(fi.Size()), nil //nolint:gosec // G115: a file size is non-negative
}

// safeDiv divides a by b, returning 0 when b is 0.
func safeDiv(a, b float64) float64 {
	if b == 0 {
		return 0
	}
	return a / b
}

// humanBytes formats a byte count with a binary (KiB/MiB/GiB) suffix.
func humanBytes(n uint64) string {
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := uint64(unit), 0
	for v := n / unit; v >= unit; v /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.2f %ciB", float64(n)/float64(div), "KMGTPE"[exp])
}
