// Example 18_oocore_pipeline — the full out-of-core (Tier 2) pipeline:
// generate a directed web-link graph as a CSV edge list, ingest it through
// the CSV reader, freeze it into a CSR snapshot, persist that snapshot as an
// on-disk csrfile, re-open the file by mmap, and run semi-external BFS plus
// PageRank directly over the mapped region.
//
// # What it demonstrates
//
// This is the complete five-stage out-of-core flow, end to end:
//
//	CSV bytes -> adjacency list -> CSR snapshot -> csrfile (disk) -> mmap -> {BFS, PageRank}
//
// Example 05 builds the adjacency directly in memory; this example extends it
// by routing the same scale-free graph through the CSV interchange stage
// first, so the whole ingest path is exercised. The CSV reader interns each
// page name to a compact NodeID and returns an in-memory adjacency list;
// [csr.BuildFromAdjList] freezes it into an immutable Tier 1 CSR snapshot;
// [csrfile.WriteToFile] persists that snapshot to disk in the Tier 2 binary
// format; and [csrfile.Open] re-attaches it by mmap. From that point the graph
// is queried straight out of the mapped pages: the semi-external
// [extern.BFSCtx] and [extern.PageRankCtx] keep only vertex-sized auxiliary
// state (a visited bitset, the rank vector) in RAM while streaming the
// adjacency from the mapped file. That is the headline out-of-core advantage
// this example measures: the on-disk adjacency dwarfs the resident heap.
//
// The csrfile preserves NodeIDs across the mmap boundary but drops the
// page-name -> NodeID mapping, so the BFS needs a known numeric seed. The
// example therefore captures the seed page's NodeID from the CSV reader's
// mapper before the adjacency (and its mapper) is discarded — exactly the
// pattern a real out-of-core consumer must follow.
//
// Alongside that transactional-style, per-edge build the example also drives
// the [bulk] high-throughput ingest path (see the "Bulk high-throughput
// ingest" section below): it re-generates the identical seeded edge stream and
// streams it straight into a [bulk.Loader], which writes a second csrfile
// directly. The two csrfiles — one built through the CSV -> CSR path, the other
// through the bulk loader — are then compared byte for byte. Because they are
// produced by two independent ingest paths yet must be identical, that
// comparison is a self-checking correctness oracle for the loader (fact
// bulk.identical), and the bulk stage reports its ingest throughput (edges/s,
// MiB/s) and on-disk size as telemetry so the fast path can be contrasted with
// the per-edge build.
//
// # Model
//
// The dataset is a directed, scale-free hyperlink graph generated by Price's
// model (de Solla Price, 1965/1976) — the directed preferential-attachment
// process that is the canonical domain for PageRank. Pages arrive in id order
// 0..N-1; each arriving page emits m citation out-links to distinct earlier
// pages, choosing each target with probability proportional to its current
// in-degree plus a small attractiveness constant a (in-degree exponent
// gamma_in = 2 + a/m). This produces a heavy-tailed in-degree distribution: a
// few early-arriving pages accrue most inbound links and become high-PageRank
// authorities, while the bulk hold near-uniform low rank. Because the
// authorities separate from the bulk by a wide margin, the top-k
// highest-PageRank node ids (tie-broken by ascending id) are a stable,
// meaningful fact.
//
// Pure citation edges always point from a newer page to an older one, which
// makes the graph a shallow DAG: forward BFS from an old page reaches almost
// nothing. To give the semi-external BFS a meaningful, stable reachable count,
// each arriving page also receives, with probability navFrac, one extra
// "navigation" link from a uniformly random earlier page (older -> newer).
// These forward links build long forward paths without disturbing the
// in-degree authority tail. The BFS is seeded from a fixed mid-graph "portal"
// page (id N/4, never the oldest page, which is a pure sink), from which a
// large but bounded fraction of the graph is reachable.
//
// Determinism. The whole graph is drawn from a single math/rand source seeded
// from cfg.seed, the build is single-threaded, edges are emitted in draw
// order, and the CSV is written in that same order — so the realised shape,
// the BFS reachable count, and the PageRank top-k are byte-identical across
// machines for a fixed -seed. Only the telemetry (lines prefixed "# ") varies
// between runs and machines.
//
// # Scale
//
// Run with no flags, the example builds a small deterministic default (4000
// pages, ~16k citation edges plus ~2k navigation edges) that completes in
// milliseconds — the size the regression test pins. The same binary scales up
// to where the out-of-core footprint advantage is observable:
//
//	go run ./examples/18_oocore_pipeline -nodes 2000000 -out-degree 8
//
// At two million pages and eight out-links each the on-disk csrfile is on the
// order of ~270 MiB while the resident rank vector is only ~16 MiB — a
// disk-over-heap advantage of roughly 17x that widens as the graph grows. The
// adjacency lives on disk, not in RAM.
//
// # Bulk high-throughput ingest (store/bulk)
//
// The [bulk] package is GoGraph's high-throughput ingest path: it streams a
// flat edge list through an in-memory adjacency list and writes the resulting
// CSR straight to a Tier 2 csrfile, the moral equivalent of running many
// txn.Commit calls back to back but at a fraction of the cost. This example
// exercises it as a second, independent build of the same graph: bulkIngest
// re-draws the identical seeded edge stream, feeds it to a [bulk.Loader] in
// batches (with the -bulk-parallel flag selecting the loader's parallel build),
// and finalises a second csrfile. It then proves the loader correct by a
// byte-for-byte comparison against the csrfile the CSV -> CSR path produced from
// the same seed — the bulk.identical fact. The stage reports ingest throughput
// (edges/s and MiB/s) and the on-disk size as "# " telemetry, and contrasts the
// bulk build's wall-clock against the per-edge CSV -> CSR -> csrfile build.
//
// DURABILITY CAVEAT — store/bulk BYPASSES THE WAL. The bulk loader is a fast
// INGEST path, not a durable transactional one. It writes the csrfile directly,
// WITHOUT going through the write-ahead log, so the module's ACID recovery
// guarantees (crash recovery by WAL replay) do NOT apply to bulk-loaded data.
// The publication of the csrfile is itself atomic and durable at the FILE level
// — [csrfile.WriteToFile] writes a temporary file, fsyncs it, renames it into
// place, and fsyncs the parent directory, so a crash mid-load leaves no partial
// file — but there is no per-transaction commit acknowledgement and no
// incremental recovery of an interrupted load: on failure you simply re-run the
// bulk load. Bulk-loaded data enters the recoverable, WAL-backed transactional
// domain only once a snapshot/checkpoint incorporates it. Use store/bulk to
// build or rebuild a graph fast from a trusted source; use the transactional
// engine when you need per-commit durability and recovery.
package main

import (
	"bytes"
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	"math/rand"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"time"

	"github.com/FlavioCFOliveira/GoGraph/examples/internal/exprof"
	"github.com/FlavioCFOliveira/GoGraph/graph"
	"github.com/FlavioCFOliveira/GoGraph/graph/csr"
	"github.com/FlavioCFOliveira/GoGraph/graph/io/csv"
	"github.com/FlavioCFOliveira/GoGraph/search/extern"
	"github.com/FlavioCFOliveira/GoGraph/store/bulk"
	"github.com/FlavioCFOliveira/GoGraph/store/csrfile"
)

// config captures every scale and shape knob of the pipeline. The zero value
// is not valid; build one with defaultConfig and override fields from flags
// (see main) or construct one directly (see the regression test).
type config struct {
	nodes        int     // number of pages in the generated web graph
	outDegree    int     // citation out-links emitted per arriving page (Price's m)
	attractive   int64   // additive attractiveness constant (Price's a; >= 0)
	navFrac      float64 // probability an arriving page also gets one forward "navigation" link
	topK         int     // number of highest-PageRank nodes to report as facts
	seed         int64   // RNG seed; fixes the deterministic data shape
	bulkParallel bool    // engage the bulk loader's parallel build (see bulkIngest)
}

// defaultConfig returns the small, deterministic default the regression test
// pins: a 4000-page scale-free web graph with four citation out-links per page
// and a navigation link on half the pages, which builds, persists, mmaps, and
// queries in milliseconds yet still separates a clear top-k of authorities
// from the bulk and yields a stable, non-trivial BFS reachable count.
func defaultConfig() config {
	return config{
		nodes:        4000,
		outDegree:    4,
		attractive:   1,
		navFrac:      0.5,
		topK:         10,
		seed:         7,
		bulkParallel: false,
	}
}

// validate rejects a configuration that cannot produce the requested shape. It
// is checked once, at the boundary, before any work. Price's model needs at
// least outDegree existing pages for the first arriving page to find distinct
// targets, so nodes must exceed outDegree; the attractiveness constant must be
// positive for the integer mixture draw to be well-defined; navFrac is a
// probability in [0,1]; and topK cannot exceed the node count.
func (c config) validate() error {
	switch {
	case c.nodes <= 0:
		return fmt.Errorf("nodes must be > 0, got %d", c.nodes)
	case c.outDegree <= 0:
		return fmt.Errorf("out-degree must be > 0, got %d", c.outDegree)
	case c.nodes <= c.outDegree:
		return fmt.Errorf("nodes (%d) must exceed out-degree (%d): not enough targets", c.nodes, c.outDegree)
	case c.attractive <= 0:
		return fmt.Errorf("attractiveness must be > 0, got %d", c.attractive)
	case c.navFrac < 0 || c.navFrac > 1:
		return fmt.Errorf("nav-frac must be within [0,1], got %g", c.navFrac)
	case c.topK <= 0:
		return fmt.Errorf("top-k must be > 0, got %d", c.topK)
	case c.topK > c.nodes:
		return fmt.Errorf("top-k (%d) exceeds nodes (%d)", c.topK, c.nodes)
	}
	return nil
}

func main() {
	cfg := defaultConfig()
	flag.IntVar(&cfg.nodes, "nodes", cfg.nodes, "number of pages in the web graph")
	flag.IntVar(&cfg.outDegree, "out-degree", cfg.outDegree, "citation out-links per arriving page (Price's m)")
	flag.Int64Var(&cfg.attractive, "attractiveness", cfg.attractive, "additive attractiveness constant (Price's a; > 0)")
	flag.Float64Var(&cfg.navFrac, "nav-frac", cfg.navFrac, "probability an arriving page also gets a forward navigation link")
	flag.IntVar(&cfg.topK, "top-k", cfg.topK, "number of highest-PageRank node ids to report")
	flag.Int64Var(&cfg.seed, "seed", cfg.seed, "RNG seed (fixes the deterministic data shape)")
	flag.BoolVar(&cfg.bulkParallel, "bulk-parallel", cfg.bulkParallel, "engage the bulk loader's parallel build for the bulk-ingest stage")
	prof := exprof.Bind(flag.CommandLine)
	flag.Parse()

	if err := prof.Run(os.Stdout, func() error {
		return run(context.Background(), os.Stdout, cfg)
	}); err != nil {
		log.Fatal(err)
	}
}

// run drives the full out-of-core pipeline described by cfg and writes a
// report to w. It generates the scale-free web graph as a CSV edge list,
// ingests it through the CSV reader, freezes the adjacency into a CSR
// snapshot, persists that snapshot as a Tier 2 csrfile, bulk-loads the same
// seeded edge stream into a second csrfile via the store/bulk high-throughput
// path and proves the two files byte-identical, then re-opens the CSV-path
// file via mmap and runs semi-external BFS plus PageRank over the mapped
// region.
//
// Bare lines carry deterministic facts (counts, the bulk-loader equivalence
// oracle, the BFS reachable count, and the PageRank top-k node ids — all
// reproducible for a fixed seed); lines prefixed with "# " carry volatile
// telemetry (per-stage wall-clock, bulk ingest throughput, and the
// disk-vs-heap footprint) that varies per run and per machine. All output goes
// to w so a test can capture and assert on the deterministic lines. run
// returns wrapped errors rather than terminating the process and honours ctx
// cancellation.
//
// Both csrfiles are written under an os.MkdirTemp directory whose absolute
// path differs on every run, so run never prints those paths; every fact line
// it emits is byte-stable.
func run(ctx context.Context, w io.Writer, cfg config) error {
	if err := cfg.validate(); err != nil {
		return fmt.Errorf("config: %w", err)
	}

	fmt.Fprintf(w, "config.nodes=%d\n", cfg.nodes)
	fmt.Fprintf(w, "config.out_degree=%d\n", cfg.outDegree)
	fmt.Fprintf(w, "config.attractiveness=%d\n", cfg.attractive)
	fmt.Fprintf(w, "config.nav_frac=%g\n", cfg.navFrac)
	fmt.Fprintf(w, "config.top_k=%d\n", cfg.topK)
	fmt.Fprintf(w, "config.seed=%d\n", cfg.seed)

	dir, err := os.MkdirTemp("", "gograph-ex18-")
	if err != nil {
		return fmt.Errorf("MkdirTemp: %w", err)
	}
	defer func() { _ = os.RemoveAll(dir) }()
	path := filepath.Join(dir, "graph.csr")

	// Stage 1 — generate the directed scale-free web graph and serialise it
	// to an in-memory CSV edge list. seedPage is the page name the BFS is
	// later seeded from; csvBytes is the size of the serialised CSV input.
	csvStart := time.Now()
	csvBuf, seedPage, genEdges := generateCSV(ctx, cfg)
	if err := ctx.Err(); err != nil {
		return err
	}
	csvBytes := uint64(csvBuf.Len()) //nolint:gosec // G115: a buffer length is non-negative

	// Stage 1 (cont.) — ingest the CSV through the edge-list reader, which
	// interns each page name to a compact NodeID and returns an in-memory
	// adjacency list.
	//
	// THE BYTE CAP IS SIZED TO THIS PAYLOAD, not left at the untrusted-input
	// default. csv.DefaultMaxBytes is 128 MiB, a deliberate memory-exhaustion
	// bound for input of unknown provenance — and the right default for a caller
	// parsing a file it did not write. This input is neither unknown nor a file:
	// generateCSV produced it in this process a few lines above, and csvBytes is
	// its exact length. Leaving the default in place capped this OUT-OF-CORE
	// pipeline — whose whole subject is data larger than memory — at about 6 M
	// edges, so `-nodes 500000 -out-degree 12` died mid-ingest with
	// ErrInputTooLarge (rmp #2375).
	//
	// The cap is RAISED, never disabled: MaxBytes <= 0 opts out of the bound
	// entirely, and an example is documentation as much as it is an exercise, so
	// it should demonstrate sizing the cap rather than removing it.
	csvOpts := csv.DefaultOptions()
	csvOpts.MaxBytes = int64(csvBytes) //nolint:gosec // G115: bounded by the buffer just written
	adj, nEdges, err := csv.ReadIntoCtx(ctx, csvBuf, csvOpts)
	if err != nil {
		return fmt.Errorf("csv.ReadIntoCtx: %w", err)
	}
	csvElapsed := time.Since(csvStart)

	// Capture the seed page's NodeID before the adjacency (and its mapper) is
	// discarded: the csrfile preserves NodeIDs across the mmap boundary but
	// drops the name -> NodeID mapping, so the BFS below needs this numeric
	// seed.
	seedID, ok := adj.Mapper().Lookup(seedPage)
	if !ok {
		return fmt.Errorf("seed page %q not interned", seedPage)
	}

	// Stage 2 — freeze the adjacency into an immutable Tier 1 CSR snapshot.
	csrStart := time.Now()
	c := csr.BuildFromAdjList(adj)
	csrElapsed := time.Since(csrStart)

	fmt.Fprintf(w, "csv.edges=%d\n", nEdges)
	fmt.Fprintf(w, "csr.order=%d\n", c.Order())
	fmt.Fprintf(w, "csr.size=%d\n", c.Size())

	// Stage 3 — write the CSR to disk in the csrfile binary format. The write
	// is atomic (write .tmp, fsync, rename). Measure the resulting on-disk
	// size: this is the adjacency footprint that, at scale, dwarfs the
	// resident auxiliary state.
	if err := ctx.Err(); err != nil {
		return err
	}
	writeStart := time.Now()
	if _, err := csrfile.WriteToFile(path, c); err != nil {
		return fmt.Errorf("csrfile.WriteToFile: %w", err)
	}
	writeElapsed := time.Since(writeStart)
	diskBytes, err := fileSize(path)
	if err != nil {
		return err
	}

	// Stage 3b — bulk ingest. Re-generate the SAME seeded edge stream and drive
	// it through the store/bulk high-throughput loader (which bypasses the
	// transactional WAL stack — see the package doc's durability caveat) into a
	// second csrfile, then compare that file byte for byte against the CSV-path
	// csrfile written above. bulkIngest returns only scalars, so the loader's
	// O(E) adjacency and CSR become unreachable before the readMem snapshot
	// below and never inflate the out-of-core heap headline.
	if err := ctx.Err(); err != nil {
		return err
	}
	bulkPath := filepath.Join(dir, "bulk.csr")
	bulkRes, err := bulkIngest(ctx, cfg, bulkPath, path)
	if err != nil {
		return fmt.Errorf("bulk ingest: %w", err)
	}
	// Deterministic bulk facts: the loader built the same vertex and edge set,
	// and the resulting csrfile is byte-identical to the CSV-path file. A change
	// in any of these three is a correctness regression in store/bulk.
	fmt.Fprintf(w, "bulk.order=%d\n", bulkRes.order)
	fmt.Fprintf(w, "bulk.size=%d\n", bulkRes.size)
	fmt.Fprintf(w, "bulk.identical=%d\n", boolToInt(bulkRes.identical))

	// Stage 4 — re-open the file via mmap and hint SEQUENTIAL access so the OS
	// reads ahead while the queries stream the adjacency. The mmap call maps
	// the whole file into the address space without reading it into the heap;
	// time it to show that re-attaching an on-disk graph is near-instant.
	mmapStart := time.Now()
	r, err := csrfile.Open(path)
	if err != nil {
		return fmt.Errorf("csrfile.Open: %w", err)
	}
	defer func() { _ = r.Close() }()
	if err := r.SetHint(csrfile.AccessSequential); err != nil {
		return fmt.Errorf("SetHint: %w", err)
	}
	mmapElapsed := time.Since(mmapStart)

	// Stage 5a — semi-external BFS from the portal page. Only the visited
	// bitset and frontier live in RAM; the adjacency streams from the mapped
	// file. BFSCtx honours ctx cancellation once per BFS level.
	bfsStart := time.Now()
	reached := 0
	if err := extern.BFSCtx(ctx, r, seedID, func(_ graph.NodeID, _ int) bool {
		reached++
		return true
	}); err != nil {
		return fmt.Errorf("extern.BFSCtx: %w", err)
	}
	bfsElapsed := time.Since(bfsStart)

	// Stage 5b — semi-external PageRank over the same mapped region. Only the
	// rank vector lives in RAM; the adjacency streams from the file each
	// iteration. PageRankCtx honours ctx cancellation at every iteration.
	prStart := time.Now()
	ranks, iters, err := extern.PageRankCtx(ctx, r, extern.DefaultPageRankOptions())
	if err != nil {
		return fmt.Errorf("extern.PageRankCtx: %w", err)
	}
	prElapsed := time.Since(prStart)

	// Resident heap after the computation, forcing a GC first so HeapAlloc
	// reflects live bytes. The rank vector is the dominant query-time
	// allocation, so its size is the in-RAM working set we contrast with the
	// on-disk adjacency.
	mem := readMem()
	rankVecBytes := uint64(len(ranks)) * 8 //nolint:gosec // G115: len is non-negative

	// Deterministic results. The BFS reachable count and the PageRank top-k
	// node ids are stable for a fixed seed; the top-k ids separate the
	// authorities from the bulk by a wide margin and ties are broken by
	// ascending id (see topPageRank).
	fmt.Fprintf(w, "bfs.seed_node=%d\n", seedID)
	fmt.Fprintf(w, "bfs.reachable=%d\n", reached)

	top := topPageRank(ranks, cfg.topK)
	if len(top) == 0 {
		return fmt.Errorf("PageRank produced no live ranks")
	}
	for i, id := range top {
		fmt.Fprintf(w, "pagerank.top%d=%d\n", i, id)
	}

	fmt.Fprintf(w, "# gen.edges=%d\n", genEdges)
	fmt.Fprintf(w, "# stage.csv_ingest=%s\n", csvElapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# stage.csr_build=%s\n", csrElapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# stage.csrfile_write=%s\n", writeElapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# stage.mmap_open=%s\n", mmapElapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# stage.bfs=%s\n", bfsElapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# stage.pagerank=%s\n", prElapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# disk.csv_input=%s\n", humanBytes(csvBytes))
	fmt.Fprintf(w, "# disk.csrfile=%s\n", humanBytes(diskBytes))
	fmt.Fprintf(w, "# mem.rank_vector=%s\n", humanBytes(rankVecBytes))
	fmt.Fprintf(w, "# mem.heap_alloc=%s\n", humanBytes(mem.HeapAlloc))
	fmt.Fprintf(w, "# ooc.disk_over_rank_vector=%.1fx\n", safeDiv(float64(diskBytes), float64(rankVecBytes)))
	fmt.Fprintf(w, "# pagerank.iterations=%d\n", iters)

	// Bulk-ingest telemetry: the high-throughput path's wall-clock, throughput
	// (edges/s and MiB/s of csrfile written), and on-disk size, plus its speedup
	// over the per-edge CSV -> CSR -> csrfile build. The bulk csrfile is
	// byte-identical to the CSV-path file, so its on-disk size matches
	// disk.csrfile; only the build cost differs.
	csvBuildTotal := csvElapsed + csrElapsed + writeElapsed
	bulkSecs := bulkRes.elapsed.Seconds()
	fmt.Fprintf(w, "# bulk.parallel=%t\n", cfg.bulkParallel)
	fmt.Fprintf(w, "# bulk.rows=%d\n", bulkRes.rows)
	fmt.Fprintf(w, "# bulk.elapsed=%s\n", bulkRes.elapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# bulk.throughput_edges_per_s=%.0f\n", safeDiv(float64(bulkRes.rows), bulkSecs))
	fmt.Fprintf(w, "# bulk.throughput_mib_per_s=%.2f\n", safeDiv(float64(bulkRes.diskBytes), bulkSecs)/(1024*1024))
	fmt.Fprintf(w, "# bulk.disk_csrfile=%s\n", humanBytes(bulkRes.diskBytes))
	fmt.Fprintf(w, "# bulk.speedup_vs_csv_build=%.2fx\n", safeDiv(float64(csvBuildTotal), float64(bulkRes.elapsed)))
	return nil
}

// generateCSV builds the directed scale-free web graph described by cfg and
// serialises it to an in-memory CSV edge list ("src,dst,1" per line). It
// returns the CSV buffer, the page name the BFS should be seeded from (id N/4,
// the mid-graph "portal"), and the number of edges written. The graph shape is
// produced by generateEdges; this wrapper only formats each edge as a CSV row
// in draw order, so the serialised CSV is byte-identical across machines for a
// fixed seed.
func generateCSV(ctx context.Context, cfg config) (*bytes.Buffer, string, int) {
	var buf bytes.Buffer
	seedPage, edges := generateEdges(ctx, cfg, func(src, dst int) {
		buf.WriteString(pageName(src))
		buf.WriteByte(',')
		buf.WriteString(pageName(dst))
		buf.WriteString(",1\n")
	})
	return &buf, seedPage, edges
}

// generateEdges draws the directed scale-free web graph described by cfg using
// Price's model (directed preferential attachment) augmented with forward
// navigation links, invoking emit for every edge in draw order. It returns the
// page name the BFS should be seeded from (id N/4, the mid-graph "portal") and
// the number of edges emitted. It is the single source of the edge stream:
// both the CSV serialisation (generateCSV) and the bulk-loader ingest
// (bulkIngest) consume it, so the two ingest paths are guaranteed to see the
// identical logical graph for a fixed seed.
//
// Pages arrive in id order. A fully-wired seed core of outDegree pages is laid
// down first so the early target draws are well-defined; then each subsequent
// page v emits outDegree citation out-links to distinct earlier pages, each
// target chosen with probability proportional to its current in-degree plus
// the attractiveness constant. With probability navFrac, page v additionally
// receives one navigation in-link from a uniformly random earlier page, giving
// the forward reachability the BFS measures.
//
// Determinism. The whole graph is drawn from a single math/rand source seeded
// from cfg.seed, the build is single-threaded, and every edge is emitted in
// the order it was drawn (never iterated from a map, whose order is randomised
// in Go) — so the edge stream, and hence every fact the pipeline reports, is
// byte-identical across machines for a fixed seed.
//
// Complexity is O(nodes * outDegree) = O(edges). The edge-copying target list
// copyTargets makes in-degree-proportional selection O(1) per pick: each
// citation edge's destination appears in it once, so a uniform draw from it is
// automatically proportional to in-degree.
func generateEdges(ctx context.Context, cfg config, emit func(src, dst int)) (string, int) {
	//nolint:gosec // G404: a seeded math/rand is intentional here — the example
	// must reproduce a fixed dataset for a given -seed; crypto/rand would defeat that.
	rng := rand.New(rand.NewSource(cfg.seed))

	edges := 0
	emitEdge := func(src, dst int) {
		emit(src, dst)
		edges++
	}

	m := cfg.outDegree
	// copyTargets holds one entry per existing citation edge: the edge's
	// destination. A page therefore appears in it exactly citation-in-degree
	// times, so a uniform draw is in-degree-proportional.
	copyTargets := make([]int, 0, cfg.nodes*m)

	// Seed core: the first m pages, wired so that page v links to every
	// earlier page u < v. This bootstraps copyTargets so the preferential
	// draws below always have a non-empty in-degree pool to sample.
	for v := 1; v < m; v++ {
		for u := 0; u < v; u++ {
			emitEdge(v, u)
			copyTargets = append(copyTargets, u)
		}
	}

	targets := make([]int, 0, m)
	seen := make(map[int]struct{}, m)
	for v := m; v < cfg.nodes; v++ {
		if v%checkEvery == 0 {
			if err := ctx.Err(); err != nil {
				return pageName(cfg.nodes / 4), edges
			}
		}
		targets = targets[:0]
		clear(seen)
		// Draw m distinct citation targets. The mixture weight at v's arrival
		// is attractive*v (one unit of attractiveness per existing page 0..v-1)
		// plus len(copyTargets) (one per existing citation edge). A single
		// integer draw over that total picks either the uniform-page branch or
		// the in-degree-proportional copy branch, with no floating-point bias.
		for len(targets) < m {
			total := cfg.attractive*int64(v) + int64(len(copyTargets))
			r := rng.Int63n(total)
			var t int
			if r < cfg.attractive*int64(v) {
				t = int(r / cfg.attractive)
			} else {
				t = copyTargets[r-cfg.attractive*int64(v)]
			}
			if t == v {
				continue // belt-and-braces: t < v always holds here
			}
			if _, dup := seen[t]; dup {
				continue // distinct citation targets per arriving page
			}
			seen[t] = struct{}{}
			targets = append(targets, t)
		}
		// Emit citations in draw order (fixed), updating copyTargets so later
		// pages see the new in-edges.
		for _, t := range targets {
			emitEdge(v, t)
			copyTargets = append(copyTargets, t)
		}
		// Navigation link: with probability navFrac, a uniformly random earlier
		// page links forward to v. This injects forward paths (older -> newer)
		// so the BFS reaches a large but bounded fraction of the graph. The
		// draw is taken unconditionally (even when it will not be used) so that
		// adding or removing navigation never shifts the citation RNG stream.
		s := rng.Intn(v)
		if rng.Float64() < cfg.navFrac {
			emitEdge(s, v)
		}
	}
	return pageName(cfg.nodes / 4), edges
}

// bulkResult carries the scalar outcome of the bulk-ingest stage. Returning
// only scalars (never the loader, its adjacency, or the built CSR) lets those
// O(V+E) structures become unreachable the moment bulkIngest returns, so the
// GC in run's readMem snapshot reclaims them and the out-of-core heap headline
// stays faithful to the CSV-path working set alone.
type bulkResult struct {
	rows      int           // edges the loader ingested
	order     uint64        // vertex count of the bulk-built CSR
	size      uint64        // edge count of the bulk-built CSR
	identical bool          // bulk csrfile is byte-for-byte equal to the reference
	diskBytes uint64        // on-disk size of the bulk csrfile
	elapsed   time.Duration // wall-clock of the whole bulk load (generate + ingest + finalise)
}

// bulkIngest drives the store/bulk high-throughput ingest path. It re-draws the
// SAME deterministic edge stream (from cfg.seed), streams it in batches into a
// bulk.Loader that bypasses the transactional WAL stack, and finalises a Tier 2
// csrfile at bulkPath. It then proves the loader correct by comparing that file
// byte for byte against refPath — the csrfile the CSV -> CSR path produced from
// the same seed. Because the two files are built by independent ingest paths yet
// must be identical, that comparison is a self-checking correctness oracle.
//
// DURABILITY CAVEAT: store/bulk bypasses the WAL, so the module's ACID recovery
// guarantees do not apply to bulk-loaded data — see the package doc's "Bulk
// high-throughput ingest" section. The csrfile publication is atomic and durable
// at the file level, but there is no per-transaction commit or WAL replay.
//
// A Finalise error, or a CSR that fails its structural self-check, is treated as
// a module bug and returned as an error. A byte mismatch is surfaced as
// identical == false, which run reports as the bulk.identical fact so the
// regression test pins it.
func bulkIngest(ctx context.Context, cfg config, bulkPath, refPath string) (bulkResult, error) {
	start := time.Now()
	l := bulk.New(bulk.Options{
		OutputPath:  bulkPath,
		Directed:    true, // matches csv.DefaultOptions: a directed simple graph
		Multigraph:  false,
		ExpectNodes: cfg.nodes,        // determinism-neutral pre-size hint (node count is known)
		Parallel:    cfg.bulkParallel, // -bulk-parallel selects the loader's parallel build
	})

	// Stream the edges into the loader in fixed-size batches (AddBatch), the
	// bulk API's high-throughput ingest entry point.
	const batchSize = 4096
	batch := make([]bulk.Edge, 0, batchSize)
	var addErr error
	flush := func() {
		if addErr != nil || len(batch) == 0 {
			return
		}
		if err := l.AddBatch(batch); err != nil {
			addErr = err
		}
		batch = batch[:0]
	}
	generateEdges(ctx, cfg, func(src, dst int) {
		if addErr != nil {
			return
		}
		batch = append(batch, bulk.Edge{Src: pageName(src), Dst: pageName(dst), Weight: 1})
		if len(batch) == batchSize {
			flush()
		}
	})
	flush()
	if addErr != nil {
		return bulkResult{}, fmt.Errorf("loader ingest: %w", addErr)
	}
	if err := ctx.Err(); err != nil {
		return bulkResult{}, err
	}

	rows, cBulk, err := l.Finalise()
	if err != nil {
		return bulkResult{}, fmt.Errorf("finalise: %w", err)
	}
	// A CSR that fails its own structural invariants would mean the loader
	// corrupted the snapshot — a module bug, not a data condition.
	if err := cBulk.Validate(); err != nil {
		return bulkResult{}, fmt.Errorf("bulk CSR failed self-validation (module bug): %w", err)
	}
	elapsed := time.Since(start)

	diskBytes, err := fileSize(bulkPath)
	if err != nil {
		return bulkResult{}, err
	}
	identical, err := filesEqual(refPath, bulkPath)
	if err != nil {
		return bulkResult{}, fmt.Errorf("compare csrfiles: %w", err)
	}
	return bulkResult{
		rows:      rows,
		order:     cBulk.Order(),
		size:      cBulk.Size(),
		identical: identical,
		diskBytes: diskBytes,
		elapsed:   elapsed,
	}, nil
}

// checkEvery bounds how often generateCSV polls ctx for cancellation: often
// enough that a cancelled multi-million-page build stops promptly, rare enough
// that the check is free relative to the surrounding work.
const checkEvery = 4096

// pageName formats a page id as a stable, zero-padded "page-NNNNNN" name. The
// fixed width keeps the CSV columns aligned and the names sortable, and the
// formatting is pure (no RNG), so it never disturbs the deterministic shape.
func pageName(id int) string {
	return "page-" + strconv.Itoa(id)
}

// topPageRank returns the ids of the k highest-PageRank live nodes, in
// descending rank order, ties broken by ascending node id. The rank slice is
// indexed by NodeID and its length is the sharded, MaxNodeID-rounded vertex
// count, so it carries ghost slots (zero rank) beyond the live nodes; those
// are skipped. The ascending-id tie-break is total and machine-independent, so
// the result is stable for a fixed seed.
func topPageRank(ranks []float64, k int) []graph.NodeID {
	type nodeRank struct {
		id   graph.NodeID
		rank float64
	}
	live := make([]nodeRank, 0, len(ranks))
	for i, x := range ranks {
		if x == 0 {
			continue
		}
		live = append(live, nodeRank{id: graph.NodeID(i), rank: x}) //nolint:gosec // G115: index is non-negative
	}
	sort.Slice(live, func(i, j int) bool {
		if live[i].rank != live[j].rank {
			return live[i].rank > live[j].rank
		}
		return live[i].id < live[j].id
	})
	if k > len(live) {
		k = len(live)
	}
	out := make([]graph.NodeID, k)
	for i := 0; i < k; i++ {
		out[i] = live[i].id
	}
	return out
}

// ─────────────────────────────────────────────────────────────────────────────
// Telemetry helpers
// ─────────────────────────────────────────────────────────────────────────────

// readMem returns a memory snapshot after forcing a GC so HeapAlloc reflects
// live (reachable) bytes rather than floating garbage.
func readMem() runtime.MemStats {
	runtime.GC()
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	return m
}

// fileSize returns the size of the file at path in bytes.
func fileSize(path string) (uint64, error) {
	fi, err := os.Stat(path)
	if err != nil {
		return 0, fmt.Errorf("stat %s: %w", filepath.Base(path), err)
	}
	return uint64(fi.Size()), nil //nolint:gosec // G115: a file size is non-negative
}

// filesEqual reports whether the files at a and b hold byte-identical content.
// It first compares sizes (cheap, and a fast reject), then streams both files
// in fixed-size chunks and compares — so the comparison stays O(1) in memory
// even when the csrfiles are hundreds of MiB, faithful to the out-of-core
// spirit of the example. It is the equivalence oracle for the bulk loader.
func filesEqual(a, b string) (bool, error) {
	sa, err := fileSize(a)
	if err != nil {
		return false, err
	}
	sb, err := fileSize(b)
	if err != nil {
		return false, err
	}
	if sa != sb {
		return false, nil
	}

	fa, err := os.Open(a) //nolint:gosec // G304: paths are example-local temp files, not user input
	if err != nil {
		return false, fmt.Errorf("open %s: %w", filepath.Base(a), err)
	}
	defer func() { _ = fa.Close() }()
	fb, err := os.Open(b) //nolint:gosec // G304: paths are example-local temp files, not user input
	if err != nil {
		return false, fmt.Errorf("open %s: %w", filepath.Base(b), err)
	}
	defer func() { _ = fb.Close() }()

	const chunk = 64 << 10
	ba := make([]byte, chunk)
	bb := make([]byte, chunk)
	for {
		na, ea := io.ReadFull(fa, ba)
		nb, eb := io.ReadFull(fb, bb)
		if !bytes.Equal(ba[:na], bb[:nb]) {
			return false, nil
		}
		if isReadEnd(ea) && isReadEnd(eb) {
			return true, nil // both streams ended together with every byte matched
		}
		if ea != nil && !isReadEnd(ea) {
			return false, fmt.Errorf("read %s: %w", filepath.Base(a), ea)
		}
		if eb != nil && !isReadEnd(eb) {
			return false, fmt.Errorf("read %s: %w", filepath.Base(b), eb)
		}
	}
}

// isReadEnd reports whether err marks a clean end of an io.ReadFull stream
// (EOF at a chunk boundary, or a short final chunk).
func isReadEnd(err error) bool {
	return errors.Is(err, io.EOF) || errors.Is(err, io.ErrUnexpectedEOF)
}

// boolToInt maps a boolean fact to the 0/1 integer the "key=int" fact format
// uses, so the regression test can assert it with parseFacts.
func boolToInt(b bool) int {
	if b {
		return 1
	}
	return 0
}

// safeDiv divides a by b, returning 0 when b is 0.
func safeDiv(a, b float64) float64 {
	if b == 0 {
		return 0
	}
	return a / b
}

// humanBytes formats a byte count with a binary (KiB/MiB/GiB) suffix.
func humanBytes(n uint64) string {
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := uint64(unit), 0
	for v := n / unit; v >= unit; v /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.2f %ciB", float64(n)/float64(div), "KMGTPE"[exp])
}
