#!/usr/bin/env bash
# release_body.sh — compose a GitHub release body that DESCRIBES what the
# release delivered, rather than pointing at a file or listing commits.
#
# Why this exists. Until v0.14.0 every release body was goreleaser's default:
# a one-line "see CHANGELOG.md for the per-release entry" plus an
# autogenerated commit list. A commit list is not a description of a
# delivery — a reader had to leave the page to learn what shipped — and ten
# of the seventeen published releases carried nothing else. This script
# makes the body self-contained, and the release workflow passes its output
# to `goreleaser --release-notes`.
#
# Usage: scripts/release_body.sh <tag> [output-file]
# The tag must have a matching `## [x.y.z]` entry in CHANGELOG.md.
set -euo pipefail

TAG="${1:?usage: release_body.sh <tag> [out]}"
OUT="${2:-/dev/stdout}"
VER="${TAG#v}"

# The changelog entry is the authoritative statement of what was delivered.
# Extract exactly this version's section: from its own heading up to the next
# top-level `## [` heading, and fail loudly rather than emit an empty body.
ENTRY="$(awk -v ver="## [$VER]" '
  index($0, ver) == 1 { inside = 1 }
  inside && /^## \[/ && index($0, ver) != 1 { exit }
  inside { print }
' CHANGELOG.md)"

if [ -z "$ENTRY" ]; then
  echo "release_body: no '## [$VER]' entry in CHANGELOG.md" >&2
  exit 1
fi

{
  printf '%s\n\n' "$ENTRY"
  printf -- '---\n\n### Further reading\n\n'
  BASE="https://github.com/FlavioCFOliveira/GoGraph/blob/$TAG"
  [ -f "release-notes/$TAG.md" ] && \
    printf '* Narrative release notes: [`release-notes/%s.md`](%s/release-notes/%s.md)\n' "$TAG" "$BASE" "$TAG"
  [ -f "docs/benchmarks/$TAG.md" ] && \
    printf '* Measured benchmark report: [`docs/benchmarks/%s.md`](%s/docs/benchmarks/%s.md)\n' "$TAG" "$BASE" "$TAG"
  printf '* Changelog file at this tag: [`CHANGELOG.md`](%s/CHANGELOG.md)\n' "$BASE"
  printf '* Commits in this release: <https://github.com/FlavioCFOliveira/GoGraph/commits/%s>\n' "$TAG"
} > "$OUT"
