// Example 05_out_of_core — Tier 2 external memory: build a scale-free web
// graph, persist its CSR adjacency as an on-disk csrfile, re-open it by
// mmap, and run semi-external PageRank directly over the mapped region.
//
// # What it demonstrates
//
// Tier 2 is GoGraph's external-memory storage tier: the CSR adjacency
// lives on disk in the csrfile binary format and is read back by mmap'ing
// the file and reinterpreting its aligned sections as typed slices in
// place — no parse, no copy into the heap. This contrasts with Tier 1, the
// fully in-memory CSR snapshot built by [csr.BuildFromAdjList]. The
// semi-external [extern.PageRankCtx] keeps only the rank vector in RAM
// (size = vertex count) while streaming the adjacency sequentially from the
// mapped file on every iteration, so the resident working set is bounded by
// the vertex count rather than the much larger edge count. That is the
// headline out-of-core advantage this example measures: the on-disk
// adjacency dwarfs the resident heap.
//
// # Model
//
// The dataset is a directed, scale-free hyperlink graph generated by
// Price's model (de Solla Price, 1965/1976) — the directed
// preferential-attachment process that is the canonical domain for
// PageRank. Nodes arrive in id order 0..N-1; each new node v emits m
// out-links, choosing each target with probability proportional to the
// target's current in-degree plus a small attractiveness constant a
// (in-degree exponent gamma_in = 2 + a/m). This produces a heavy-tailed
// in-degree distribution: a few early-arriving nodes accrue most of the
// incoming links and become high-PageRank authorities, while the bulk hold
// near-uniform low rank.
//
// Because the authorities separate from the bulk by a wide margin, the
// top-k highest-PageRank node ids (tie-broken by ascending id) are a
// stable, meaningful fact — unlike a uniform ring, whose PageRank is flat
// and has no ranking to report. Fixing -seed fixes the data shape, and
// therefore the top-k, exactly: the generator draws from a single seeded
// math/rand source, emits each node's targets in draw order, and the
// semi-external PageRank sums in a fixed CSR-row order, so the deterministic
// facts are byte-identical across machines.
//
// # Scale
//
// Run with no flags, the example builds a small deterministic default
// (5000 nodes, ~20k edges) that completes in milliseconds — the size the
// regression test pins. The same binary scales up to where the out-of-core
// footprint advantage is observable:
//
//	go run ./examples/05_out_of_core -nodes 1000000 -out-degree 8
//
// At one million nodes and eight out-links each the on-disk csrfile is on
// the order of ~69 MiB while the resident rank vector is only ~8 MiB — the
// adjacency lives on disk, not in RAM. Every dimension is a flag, and only
// the telemetry (lines prefixed "# ") varies between runs and machines; the
// fact lines are reproducible for a fixed -seed.
package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"log"
	"math/rand"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"time"

	"github.com/FlavioCFOliveira/GoGraph/graph"
	"github.com/FlavioCFOliveira/GoGraph/graph/adjlist"
	"github.com/FlavioCFOliveira/GoGraph/graph/csr"
	"github.com/FlavioCFOliveira/GoGraph/search/extern"
	"github.com/FlavioCFOliveira/GoGraph/store/csrfile"
)

// config captures every scale and shape knob of the example. The zero
// value is not valid; build one with defaultConfig and override fields
// from flags (see main) or construct one directly (see the regression
// test).
type config struct {
	nodes      int   // number of vertices in the generated web graph
	outDegree  int   // out-links emitted per arriving node (Price's m)
	attractive int64 // additive attractiveness constant (Price's a; >= 0)
	topK       int   // number of highest-PageRank nodes to report as facts
	seed       int64 // RNG seed; fixes the deterministic data shape
}

// defaultConfig returns the small, deterministic default the regression
// test pins: a 5000-node scale-free web graph with four out-links per
// node, which builds and ranks in milliseconds yet still separates a clear
// top-k of authorities from the bulk.
func defaultConfig() config {
	return config{
		nodes:      5000,
		outDegree:  4,
		attractive: 1,
		topK:       10,
		seed:       7,
	}
}

// validate rejects a configuration that cannot produce the requested
// shape. It is checked once, at the boundary, before any work. Price's
// model needs at least outDegree existing nodes for the first arriving
// node to find distinct targets, so nodes must exceed outDegree; the
// attractiveness constant must be non-negative for the mixture weight to
// be well-defined; and topK cannot exceed the node count.
func (c config) validate() error {
	switch {
	case c.nodes <= 0:
		return fmt.Errorf("nodes must be > 0, got %d", c.nodes)
	case c.outDegree <= 0:
		return fmt.Errorf("out-degree must be > 0, got %d", c.outDegree)
	case c.nodes <= c.outDegree:
		return fmt.Errorf("nodes (%d) must exceed out-degree (%d): not enough targets", c.nodes, c.outDegree)
	case c.attractive < 0:
		return fmt.Errorf("attractiveness must be >= 0, got %d", c.attractive)
	case c.topK <= 0:
		return fmt.Errorf("top-k must be > 0, got %d", c.topK)
	case c.topK > c.nodes:
		return fmt.Errorf("top-k (%d) exceeds nodes (%d)", c.topK, c.nodes)
	}
	return nil
}

func main() {
	cfg := defaultConfig()
	flag.IntVar(&cfg.nodes, "nodes", cfg.nodes, "number of vertices in the web graph")
	flag.IntVar(&cfg.outDegree, "out-degree", cfg.outDegree, "out-links per arriving node (Price's m)")
	flag.Int64Var(&cfg.attractive, "attractiveness", cfg.attractive, "additive attractiveness constant (Price's a; >= 0)")
	flag.IntVar(&cfg.topK, "top-k", cfg.topK, "number of highest-PageRank node ids to report")
	flag.Int64Var(&cfg.seed, "seed", cfg.seed, "RNG seed (fixes the deterministic data shape)")
	flag.Parse()

	if err := run(context.Background(), os.Stdout, cfg); err != nil {
		log.Fatal(err)
	}
}

// run generates the scale-free web graph described by cfg, freezes it into
// a CSR snapshot, persists it as a Tier 2 csrfile, re-opens the file via
// mmap, runs semi-external PageRank over the mapped region, and writes a
// report to w. Bare lines carry deterministic facts (counts and the top-k
// node ids, reproducible for a fixed seed); lines prefixed with "# " carry
// volatile telemetry (durations and the disk-vs-heap footprint) that varies
// per run and per machine. All output goes to w so a test can capture and
// assert on the deterministic lines. run returns wrapped errors rather than
// terminating the process and honours ctx cancellation.
//
// The csrfile is written under an os.MkdirTemp directory whose absolute
// path differs on every run, so run never prints that path; every fact line
// it emits is byte-stable.
func run(ctx context.Context, w io.Writer, cfg config) error {
	if err := cfg.validate(); err != nil {
		return fmt.Errorf("config: %w", err)
	}

	fmt.Fprintf(w, "config.nodes=%d\n", cfg.nodes)
	fmt.Fprintf(w, "config.out_degree=%d\n", cfg.outDegree)
	fmt.Fprintf(w, "config.attractiveness=%d\n", cfg.attractive)
	fmt.Fprintf(w, "config.top_k=%d\n", cfg.topK)
	fmt.Fprintf(w, "config.seed=%d\n", cfg.seed)

	dir, err := os.MkdirTemp("", "gograph-ex05-")
	if err != nil {
		return fmt.Errorf("MkdirTemp: %w", err)
	}
	defer func() { _ = os.RemoveAll(dir) }()
	path := filepath.Join(dir, "graph.csr")

	// Generate the directed scale-free adjacency in memory, then freeze it
	// into an immutable Tier 1 CSR snapshot.
	genStart := time.Now()
	a, err := generate(ctx, cfg)
	if err != nil {
		return fmt.Errorf("generate: %w", err)
	}
	c := csr.BuildFromAdjList(a)
	genElapsed := time.Since(genStart)

	fmt.Fprintf(w, "csr.order=%d\n", c.Order())
	fmt.Fprintf(w, "csr.size=%d\n", c.Size())

	// Tier 2 — write the CSR to disk in the csrfile binary format. The
	// write is atomic (write .tmp, fsync, rename). Measure the resulting
	// on-disk size: this is the adjacency footprint that, at scale, dwarfs
	// the resident rank vector.
	if err := ctx.Err(); err != nil {
		return err
	}
	if _, err := csrfile.WriteToFile(path, c); err != nil {
		return fmt.Errorf("csrfile.WriteToFile: %w", err)
	}
	diskBytes, err := fileSize(path)
	if err != nil {
		return err
	}

	// Re-open the file via mmap and hint SEQUENTIAL access so the OS reads
	// ahead while PageRank streams the adjacency. The mmap call maps the
	// whole file into the address space without reading it into the heap;
	// time it to show that re-attaching an on-disk graph is near-instant.
	mmapStart := time.Now()
	r, err := csrfile.Open(path)
	if err != nil {
		return fmt.Errorf("csrfile.Open: %w", err)
	}
	defer func() { _ = r.Close() }()
	if err := r.SetHint(csrfile.AccessSequential); err != nil {
		return fmt.Errorf("SetHint: %w", err)
	}
	mmapElapsed := time.Since(mmapStart)

	// Semi-external PageRank: only the rank vector lives in RAM; the
	// adjacency streams from the mapped file each iteration. PageRankCtx
	// honours ctx cancellation at every iteration boundary.
	prStart := time.Now()
	ranks, iters, err := extern.PageRankCtx(ctx, r, extern.DefaultPageRankOptions())
	if err != nil {
		return fmt.Errorf("extern.PageRankCtx: %w", err)
	}
	prElapsed := time.Since(prStart)

	// Resident heap after the computation: forcing a GC first so HeapAlloc
	// reflects live bytes. The rank vector is the dominant query-time
	// allocation, so its size is the in-RAM working set we contrast with the
	// on-disk adjacency.
	mem := readMem()
	rankVecBytes := uint64(len(ranks)) * 8 //nolint:gosec // G115: len is non-negative

	// Rank the live nodes and emit the top-k node ids as deterministic
	// facts. The ids separate the authorities from the bulk by a wide
	// margin, so the top-k is stable for a fixed seed; ties are broken by
	// ascending id (see topPageRank).
	top := topPageRank(ranks, cfg.topK)
	if len(top) == 0 {
		return fmt.Errorf("PageRank produced no live ranks")
	}
	for i, id := range top {
		fmt.Fprintf(w, "pagerank.top%d=%d\n", i, id)
	}

	fmt.Fprintf(w, "# build.elapsed=%s\n", genElapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# build.edge_rate=%.0f edges/s\n", rate(int(c.Size()), genElapsed)) //nolint:gosec // G115: edge count fits int
	fmt.Fprintf(w, "# disk.csrfile=%s\n", humanBytes(diskBytes))
	fmt.Fprintf(w, "# mem.rank_vector=%s\n", humanBytes(rankVecBytes))
	fmt.Fprintf(w, "# mem.heap_alloc=%s\n", humanBytes(mem.HeapAlloc))
	fmt.Fprintf(w, "# ooc.disk_over_rank_vector=%.1fx\n", safeDiv(float64(diskBytes), float64(rankVecBytes)))
	fmt.Fprintf(w, "# mmap.elapsed=%s\n", mmapElapsed.Round(time.Microsecond))
	fmt.Fprintf(w, "# pagerank.iterations=%d\n", iters)
	fmt.Fprintf(w, "# pagerank.elapsed=%s\n", prElapsed.Round(time.Microsecond))
	return nil
}

// generate builds the directed scale-free web graph described by cfg using
// Price's model (directed preferential attachment). Nodes arrive in id
// order: a fully-wired seed core of outDegree nodes is laid down first so
// the early target draws are well-defined, then each subsequent node v
// emits outDegree out-links to distinct earlier nodes, choosing each target
// with probability proportional to its current in-degree plus the
// attractiveness constant.
//
// Determinism. The whole graph is drawn from a single math/rand source
// seeded from cfg.seed, the build is single-threaded, and each node's
// targets are emitted in the order they were drawn (never iterated from a
// map, whose order is randomised in Go) — so the realised shape, and hence
// the PageRank top-k, is byte-identical across machines for a fixed seed.
//
// Complexity is O(nodes * outDegree) = O(edges). The edge-copying target
// list copyTargets makes in-degree-proportional selection O(1) per pick:
// each existing edge's destination appears in it once, so a uniform draw
// from it is automatically proportional to in-degree.
func generate(ctx context.Context, cfg config) (*adjlist.AdjList[uint32, struct{}], error) {
	//nolint:gosec // G404: a seeded math/rand is intentional here — the example
	// must reproduce a fixed dataset for a given -seed; crypto/rand would defeat that.
	rng := rand.New(rand.NewSource(cfg.seed))
	a := adjlist.New[uint32, struct{}](adjlist.Config{Directed: true})

	m := cfg.outDegree
	// copyTargets holds one entry per existing directed edge: the edge's
	// destination. A node therefore appears in it exactly in-degree times.
	copyTargets := make([]uint32, 0, cfg.nodes*m)

	// Seed core: the first m nodes, wired so that node v links to every
	// earlier node u < v. This bootstraps copyTargets so the preferential
	// draws below always have a non-empty in-degree pool to sample.
	for v := 1; v < m; v++ {
		for u := 0; u < v; u++ {
			if err := a.AddEdge(uint32(v), uint32(u), struct{}{}); err != nil { //nolint:gosec // G115: bounded by cfg.nodes
				return nil, fmt.Errorf("AddEdge %d->%d: %w", v, u, err)
			}
			copyTargets = append(copyTargets, uint32(u)) //nolint:gosec // G115: u < v <= nodes
		}
	}

	targets := make([]uint32, 0, m)
	seen := make(map[uint32]struct{}, m)
	for v := m; v < cfg.nodes; v++ {
		if v%checkEvery == 0 {
			if err := ctx.Err(); err != nil {
				return nil, err
			}
		}
		targets = targets[:0]
		clear(seen)
		// Draw m distinct targets. The mixture weight at v's arrival is
		// attractive*v (one unit of attractiveness per existing node 0..v-1)
		// plus len(copyTargets) (one per existing edge). A single integer
		// draw over that total picks either the uniform-node branch or the
		// in-degree-proportional copy branch, with no floating-point bias.
		for len(targets) < m {
			total := cfg.attractive*int64(v) + int64(len(copyTargets))
			r := rng.Int63n(total)
			var t uint32
			if r < cfg.attractive*int64(v) {
				t = uint32(r / cfg.attractive) //nolint:gosec // G115: r/attractive < v <= nodes
			} else {
				t = copyTargets[r-cfg.attractive*int64(v)]
			}
			if int(t) == v {
				continue // belt-and-braces: t < v always holds here
			}
			if _, dup := seen[t]; dup {
				continue // distinct targets per arriving node
			}
			seen[t] = struct{}{}
			targets = append(targets, t)
		}
		// Emit in draw order (fixed), updating copyTargets so later nodes see
		// the new in-edges.
		for _, t := range targets {
			if err := a.AddEdge(uint32(v), t, struct{}{}); err != nil { //nolint:gosec // G115: bounded by cfg.nodes
				return nil, fmt.Errorf("AddEdge %d->%d: %w", v, t, err)
			}
			copyTargets = append(copyTargets, t)
		}
	}
	return a, nil
}

// checkEvery bounds how often generate polls ctx for cancellation: often
// enough that a cancelled multi-million-node build stops promptly, rare
// enough that the check is free relative to the surrounding work.
const checkEvery = 4096

// topPageRank returns the ids of the k highest-PageRank live nodes, in
// descending rank order, ties broken by ascending node id. The rank slice
// is indexed by NodeID and its length is the sharded, MaxNodeID-rounded
// vertex count, so it carries ghost slots (zero rank) beyond the live
// nodes; those are skipped. The ascending-id tie-break is total and
// machine-independent, so the result is stable for a fixed seed.
func topPageRank(ranks []float64, k int) []graph.NodeID {
	type nodeRank struct {
		id   graph.NodeID
		rank float64
	}
	live := make([]nodeRank, 0, len(ranks))
	for i, x := range ranks {
		if x == 0 {
			continue
		}
		live = append(live, nodeRank{id: graph.NodeID(i), rank: x}) //nolint:gosec // G115: index is non-negative
	}
	sort.Slice(live, func(i, j int) bool {
		if live[i].rank != live[j].rank {
			return live[i].rank > live[j].rank
		}
		return live[i].id < live[j].id
	})
	if k > len(live) {
		k = len(live)
	}
	out := make([]graph.NodeID, k)
	for i := 0; i < k; i++ {
		out[i] = live[i].id
	}
	return out
}

// ─────────────────────────────────────────────────────────────────────────────
// Telemetry helpers
// ─────────────────────────────────────────────────────────────────────────────

// readMem returns a memory snapshot after forcing a GC so HeapAlloc
// reflects live (reachable) bytes rather than floating garbage.
func readMem() runtime.MemStats {
	runtime.GC()
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	return m
}

// fileSize returns the size of the file at path in bytes.
func fileSize(path string) (uint64, error) {
	fi, err := os.Stat(path)
	if err != nil {
		return 0, fmt.Errorf("stat %s: %w", filepath.Base(path), err)
	}
	return uint64(fi.Size()), nil //nolint:gosec // G115: a file size is non-negative
}

// rate returns count/elapsed in units per second, or 0 for a zero-length
// interval.
func rate(count int, elapsed time.Duration) float64 {
	if elapsed <= 0 {
		return 0
	}
	return float64(count) / elapsed.Seconds()
}

// safeDiv divides a by b, returning 0 when b is 0.
func safeDiv(a, b float64) float64 {
	if b == 0 {
		return 0
	}
	return a / b
}

// humanBytes formats a byte count with a binary (KiB/MiB/GiB) suffix.
func humanBytes(n uint64) string {
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := uint64(unit), 0
	for v := n / unit; v >= unit; v /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.2f %ciB", float64(n)/float64(div), "KMGTPE"[exp])
}
